### ISSUE TITLE
[utilities.print] Is utilities the right layer for print?

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/inuitcss#100]
Maybe it's just me, but it *feels* weird. It is not really an utility class, judging by [the definition](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#utility-namespaces-u-). It made sense for it to be in this layer back when the layer was called `trumps`, but now it kinda does not. 

So, is the `generic` layer the right place for this file? In that case, the question is if order of appearance in css would actually make things worse?

**Comment by anselmh** [comment]
True, I can understand your point and think generic would indeed make sense.

**Comment by florianbouvot** [comment]
Right, "it's the excepiton that proves the rule" 😆 : generic layer seem suitable.

**Comment by csshugs** [comment]
@nenadjelovac @anselmh @florianbouvot 
But wouldn't it violate the idea of itcss/the specificity graph? Due to the [`!important`](https://github.com/inuitcss/inuitcss/blob/e97c17bd1942e91cfc048e04673659fb5ba6e347/utilities/_utilities.print.scss#L22-L25) declarations there would be a peak in the specificity graph. And also those declarations which don't carry an `!important` are likely to be ’trumped’ further down the line of `@imported` SCSS partials.

It has to be in utilities because it needs to ’trump’ the declarations of identical selectors.

**Comment by anselmh** [comment]
Print, since it is its own media type, doesn’t violate the idea of the specificity graph. Actually, I’d not take print styles into account at all for it.

**Comment by csshugs** [comment]
@anselmh 
>Print, since it is its own media type, doesn’t violate the idea of the specificity graph. Actually, I’d not take print styles into account at all for it.

Ok agree, but to my second point:

Take [this code](https://github.com/inuitcss/inuitcss/blob/e97c17bd1942e91cfc048e04673659fb5ba6e347/utilities/_utilities.print.scss#L29-L32) for example. When I write in my elements layer file `elements.link`:

```scss
a,
a:visited {
  text-decoration: none;
}
```

...it gets trumped in `utitlities.print` with [this](https://github.com/inuitcss/inuitcss/blob/e97c17bd1942e91cfc048e04673659fb5ba6e347/utilities/_utilities.print.scss#L29-L32) which is good and exactly what I want. 
But when we transfer the print partial into the generic layer, that line of code to complement our print styles (in our case for `a, a:visited`) is later overridden with our styles in `elements.link` (for all media included print) which is not what we want. We definitely want `text-decoration: underline` for print, but we would (potentially) override it ourselves when we transfer the print styles into the generic layer.

**Comment by florianbouvot** [comment]
I'm even more confused... 😕

**Comment by anselmh** [comment]
@csshugs I’m in favour of adding `!important` to all print styles anyways since they are the ultimate rules for print, and any non-print styles should never override them at any point.

**Comment by nenadjelovac** [comment]
I've digged a little deeper, and here's what I've found about ITCSS (inuitcss) layers:

>**1) Generic to explicit**

>We start out with the most generic, low-level, catch-all, unremarkable styles, and eventually progress to more explicit and specific rules as we move through the project. We might start with our reset, then progress to slightly more scoped rules like h1–6 {}, right through to extremely explicit rules such as .text-center {}.

>**2) Low specificity to high specificity**

>The lowest-specificity selectors appear towards the beginning, with specificity steadily increasing as we progress through the project. We want to ensure that we avoid as much of the Specificity Wars as we can, so we try and refrain from writing higher-specificity selectors before lower-specificity ones. We're always adding specificity in the same direction, thus avoiding conflicts.

>**3) Far-reaching to localised**
>Selectors towards the beginning of the project affect a lot of the DOM, with that reach being progressively lessened as we go through the codebase. We want to make 'passes' over the DOM by writing rules that affect progressively less and less of it.

>We might start by wiping the margins and paddings off everything, then we might style every type of element, then narrow that down to every type of element with a certain class applied to it, and so on. It is this gradual narrowing of reach that gives us the triangle shape.

Taken from [Manage large CSS projects with ITCSS](http://www.creativebloq.com/web-design/manage-large-css-projects-itcss-101517528).

More from the same source:

>The Generic layer is the first one that actually produces any CSS. It houses very high-level, far reaching styles. **This layer is seldom modified, and is usually the same across any projects you work on.** It contains things like Normalize.css, global box-sizing rules, CSS resets and so on. The Generic layer affects a lot of the DOM, hence it being nice and wide in the Triangle model, and occurring very early on.

Now, about the specificity, it shouldn't be that much of an issue according to the excerpt from [The Specificity Graph](http://csswizardry.com/2014/10/the-specificity-graph/#addendum--26-november-2014). Please read the whole addendum because I don't want to copy/paste the whole block of text here (and because Harry left great emphasis there). 

---

So it is my conclusion that print should probably needs to go in generic layer (with @anselmh's suggestion in previous comment). 

@csswizardry we need your take on this.

**Comment by dnixx** [comment]
I think the print styles should be included in the specificity graph. They don't affect the specificity graph for screen media, but certainly for print media, which I don't think should be treated any differently.

A project can contain many more print styles than the generic ones, e.g. class selectors, which could very well lead to specificity issues.

If we explicitly set anchor `text-decoration` to `none` in the element layer for *all* media (which is happening now), I think we should do the exact same thing for print media: put any overrides in the same layer.

This is what we would do in the component layer, and what we do for other (width-based) media queries.

This may not be the most pragmatic solution, though. Because I usually don't include many print styles I'd probably just put the current `utilities.print` at the end of the style sheet with lots of `!important`s :\

**Comment by csswizardry** [comment]
It needs to stay in Utilities. As discussed, _Trumps_ is the most accurate name for this later, but we decided to rename it and this is one of the tradeoffs we’ll have to make.

**Comment by nenadjelovac** [comment]
@csswizardry 
>Trumps is the most accurate name for this layer

Yes, I had the feeling we're lacking that layer now, but didn't want to suggest introducing another layer just for one file.

Actually, I don't have a strong opinion of this, just wanted to share my views regarding the definition. It might just be a semantic thing, but in practice the tradeoff seem better for the time being.

I'll close the issue if @inuitcss/core agrees.

**Comment by csshugs** [comment]
Agreed.

**Comment by dalemartyn** [comment]
Wouldn't it make sense from an ITCSS perspective to split the print styles up in to the elements layer? So for example, _elements.tables.scss would become:

```
/* ==========================================================================
   #TABLES
   ========================================================================== */

/**
 * 1. Ensure tables fill up as much space as possible.
 */

table {
  width: 100%; /* [1] */
}


@media print {

  /**
   * Printing Tables: http://css-discuss.incutio.com/wiki/Printing_Tables
   */

  thead {
    display: table-header-group;
  }

  tr {
    page-break-inside: avoid;
  }

}
```

or is there a good reason not to do this?

**Comment by herzinger** [comment]
> [...] is there a good reason not to do this?
- @dalemartyn 

There's a whole discussion about that in this very page, including the input of @csswizardry, the author of inuit and ITCSS. If you read it all and don't agree, it's quite easy to implement your preferred way, and I encourage you to do so. That goes for anything in the framework: You should use it in the way you believe is right for you. The arguments on why it is the way it is here were made.

**Comment by dalemartyn** [comment]
hi @herzinger , 

thanks for your response. I did see the discussion on this page, but it is about putting the full print styles in the generic layer, which would cause issues as it comes before the elements layer. I was wondering about putting all the print styles in the elements layer, so they come immediately after each elements styles, and therefore won't be overridden. I agree, I can implement this myself, was just curious if anyone could see a good reason why I shouldn't do it?

**Comment by herzinger** [comment]
The print styles will overwrite anything else, no matter the layer, since it's all within media-queries, so it's all a matter of semantics mostly. The idea behind ITCSS is that each layer has more specificity than the previous one, and since all the print stiles are meant to trump over anything else, it goes on the last layer, originally called 'trumps' and later renamed 'utilities'. But in practice, it'll work the same in any layer if it's done right. That's the TL;DR.
