### ISSUE TITLE
Add a composer.json file

### ISSUE THREAD

**Issue by jonsa** [inuitcss/inuitcss#110]
.. and register the project on [Packagist](https://packagist.org/).

**Comment by florianbouvot** [comment]
Is composer for really useful for this kind of project?

**Comment by jonsa** [comment]
Ah, I was looking at the beta2 release I had downloaded and there were no dependencies defined, which would have made it easy. But it's still doable.

I prefer to work with one package manager when I work with projects. Be it NuGet for .NET, Composer for PHP or bower for JS. Both Bootstrap ([nuget](https://www.nuget.org/packages/bootstrap/4.0.0-alpha3) [packagist](https://packagist.org/packages/twbs/bootstrap)) and Foundation ([nuget](https://www.nuget.org/packages/Foundation5.MVC.Sass/) [packagist](https://packagist.org/packages/zurb/foundation)) exists on the mentioned package managers and I find it great that I, as a developer, don't have to jump through hoops to get my required packages.

To be fair, to say that it requires npm is just wrong. It requires a preprocessor that can handle scss and those are implemented in many languages, including PHP. [sassphp](https://github.com/sensational/sassphp) which wraps around libsass and the pure PHP implementation [scssphp](https://github.com/leafo/scssphp).

**Comment by anselmh** [comment]
Okay, thanks for the elaboration to understand your point a bit better. I think it makes sense to leave this open and try to get some feedback if other people would like to have this as well and what’s common practice. I’ll do this and get back to you when I have more feedback. :)

**Comment by anselmh** [comment]
After doing a survey on Twitter (result >75% saying not useful to have it on such registries) and reviewing again the numbers of bootstrap and foundation on these registries I think it would make sense to publish inuit on these package managers as well.

@inuitcss/core please add 👍 if you agree or 👎 if you disagree.

One major concern here though is that we now have a dependency specified which would need to be published on these package managers as well. It’s referenced here https://github.com/inuitcss/inuitcss/blob/develop/package.json#L32 (respectively in the `bower.json` for bower). @jonsa because of that, even if we’ll agree, I cannot promise anything.

**Comment by florianbouvot** [comment]
@jonsa 
> Be it NuGet for .NET, Composer for PHP or bower for JS.

Bower for "front-end", npm for JS.

I vote 👎 because I think that "normal" to use the "correct" package manager: when I work with back-end developer we need to use composer + npm ...

**Comment by anselmh** [comment]
> npm for JS

Just for sake of completeness: npm _was thought_ for for node.js applications, not for JS. ;)

**Comment by csshugs** [comment]
I've slightly reconsidered my point of view and am now against juggling around with another package manager which isn't even thought for this kind of project. The dependency of Sass-MQ is to error-prone IMO. I wouldn't want to introduce such a potential point of failure. 

And I don't care if Bootstrap and Foundation are published at Packagist, because we don't want to be Bootstrap or Foundation 😜

**Comment by florianbouvot** [comment]
@csshugs good point. 
Like before I'm against adding `composer.json` file for this project.

**Comment by tymondesigns** [comment]
No need for composer/packagist integration. Doesn't make sense for front end packages imo.
