### ISSUE TITLE
[objects.flag] Align `--rev` modifier naming with other objects

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#114]
The flag modifier for reversed order of image and body is named `.o-flag--rev` at the moment.

The appropriate modifiers for [`objects.layout`](https://github.com/inuitcss/inuitcss/blob/419f285b6f3bc67a43536d2c332d9deead432fdb/objects/_objects.layout.scss#L240) and [`objects.media`](https://github.com/inuitcss/inuitcss/blob/419f285b6f3bc67a43536d2c332d9deead432fdb/objects/_objects.media.scss#L128) are named `--reverse`.

Should we rename the flag modifier from `.o-flag--rev` to `.o-flag--reverse` to align the naming with the other modules?

**Comment by nenadjelovac** [comment]
@csshugs +1!

**Comment by florianbouvot** [comment]
I wonder if it will not be better to use `--rev` instead of `reverse` for compatibility with pre-alpha version: [objects.layout](https://github.com/inuitcss/objects.layout/blob/master/_objects.layout.scss), [objects.media](https://github.com/inuitcss/objects.media/blob/master/_objects.media.scss), [objects.flag](https://github.com/inuitcss/objects.flag/blob/master/_objects.flag.scss).

**Comment by nenadjelovac** [comment]
@florianbouvot I'd personally go with breaking backwards compatibility in favour of more clear class name. Yes, it's not ideal to break the compatibility, but we have the chance to move forward with better version of inuit, so why not do it? :)

**Comment by florianbouvot** [comment]
@nenadjelovac ok, I just wanted to point this 😉

**Comment by csshugs** [comment]
@florianbouvot 
I'm with @nenadjelovac here, so I'll merge #115
