### ISSUE TITLE
[proposal] move src files into own folder

### ISSUE THREAD

**Issue by tymondesigns** [inuitcss/inuitcss#142]
As per my comment here https://github.com/inuitcss/inuitcss/pull/134#issuecomment-238387049

I now think it would make sense to place the sass source files in a separate folder so the root doesn't get muddied up by other unrelated folders and files.

Any objections?

**Comment by florianbouvot** [comment]
I have no opinion, it'll add one level in path that user need to type/copy:

@import "`node_modules/inuitcss/scr/objects/_objects.layout.scss`";

**Comment by anselmh** [comment]
True, thinking about this again I think since this would be only to separate test from src it’s not necessary to do this.

**Comment by area73** [comment]
To me it is more clear to have all the scss files under src because people that are new to this framework may be confuse if they find folders like "settings" or "generic".
Besides that , I don't know if you are planning to have also a "doc" file with *.md files inside (many bower components have that folder, thake a look at Chart.js) or a "samples" dir.

**Comment by florianbouvot** [comment]
@area73 I use this tree approach in my "final" project but for inuitcss I think it's not needed.

I think documentation will be manage in an other repo 😉

**Comment by florianbouvot** [comment]
@inuitcss/core I think we can close this issue for now?

**Comment by tymondesigns** [comment]
Yea ok, I'm all turned around on this :+1:
