### ISSUE TITLE
posible use of a tool to document i.e. sassdoc

### ISSUE THREAD

**Issue by area73** [inuitcss/inuitcss#150]
Have you consider the use of a tool to generate docs for sass files like sassdoc ?

**Comment by csshugs** [comment]
@area73 
IMO sassdoc would be an overhead because we have very little Sass functionality which needs documentation. Apart from that we would have to completely change our commenting style 😞 

In a custom, large scale project, sassdoc surely proves itself useful, especially when there are more developers involved. But since inuitcss is third-party code in such projects, I don't see any need to document the framework code itself with sassdoc. As framework user, everything you'll need to know about inuitcss will be provided on the documentation site when it's done.

**Comment by florianbouvot** [comment]
@csshugs I agree with you 😉

**Comment by csshugs** [comment]
Maybe we change our minds in the future. But for now, I close this.

But thanks @area73 for bringing this up!
