### ISSUE TITLE
Naming/Organisation Confusion

### ISSUE THREAD

**Issue by aaronstezycki** [inuitcss/inuitcss#177]
I know documentation is coming on this, but maybe you can point me the right direction of existing documentation on csswizardry.com? This side of inuit at the minute is confusing as hell without any documentation.

So far I've gathered that;
- All objects are (i.e like the box object) are un-styled pieces of code.
- All components are (i.e. buttons) are styled pieces of code.
  (hence the button move from objects to components)

So my main.scss currently looks like ...

```
// OBJECTS (unstyled)
@import "bower_components/objects/objects.box";

* COMPONENTS (styled)
@import "bower_components/components/components.buttons";
```

So if I want to create a few modifiers for the box object, such as `.box--border` and `.box--shadow`, which are stylistic modifiers, where does that code go? Am I now making the box object a component?

Now my file structure looks like ...

```
// OBJECTS
@import "bower_components/objects/objects.box";

// COMPONENTS
@import "bower_components/components/components.buttons";
@import "components/components.box";
```

I'm not sure the differentiation between objects and components is large enough to justify the difference in category. I'd much prefer that if files are similar in purpose to sit alongside each other. Plus I tend to put the categories in to directories too so that all objects are under one directory, and all components are in one directory.

```
// OBJECTS (unstyled)
@import "bower_components/objects/objects.box";
@import "objects/objects.box.modifiers";                                         // Modifiers

// COMPONENTS (styled)
@import "bower_components/components/components.buttons";

```

Sorry, just a bit confused here with what I *should* be doing, over what I *prefer* doing.

**Comment by herzinger** [comment]
I think you should always go with whatever you are not comfortable with, but in this case your understanding of the concepts of objects and components is off. Some links:

[oocss](https://goo.gl/CwiIIu)
[ITCSS](https://www.youtube.com/watch?v=1OKZOV-iLj4)
[BEMIT](goo.gl/WCt3Fa)
[namespacing](http://goo.gl/WCt3Fa)

In the case you asked about, you wouldn't modify the box object that way. An object is an abstraction you can reuse in a generic way. You could have a "card" component with the box object as it's base, for example.

**Comment by aaronstezycki** [comment]
I've read those links, but I don't think this is covered entirely. Seems very long winded to create a simple box object with a border, by creating a new 'card component' resulting in `.box .card--border`.   I might as well just make the entire '.box' object myself with modifiers and not including inuits. If I have to create everything myself... what's the point of using Inuit?

**Comment by herzinger** [comment]
Okay, it's not easy. inuitcss is built in conformation with @csswizardry's ITCSS, so some things will be hard to understand if you don't wrap your head around that philosophy as well. The box object, as with any object, in aimed to be used with as much versatility as possible. It's a shortcut of sorts, that adds to any element block level display, some padding, a clearfix and removes the margin bottom of the last of it's type in a sequence. This is a pattern that we use a lot, so an object makes so we don't need to rewrite all of that every time. It has no other cosmetic styling, so you can reuse it in any way, independently of the look of the component you are styling.

So let's say, you are writing a component that is only a boxed card with a border around. You have two options: 
1. Create a `.o-box--bordered` modifier (which I don't recommend, since that is adding cosmetic styling, but is not wrong;
2. Create a 'c-card' (or something) with only `border: 1px solid #000;` (or something) and use `<div class="o-box o-card">something something</div>`

I guess if your use case is that simple, you could also use a `.u-bordered` utility class or something.

I hope it's a little easier to understand like this.

**Comment by aaronstezycki** [comment]
It just seems a little complicated, what if the card has a shadow but no border? In my experience, you create the overall layout and then create modifiers to change the behaviour in certain circumstances.

`o-box o-box--shadow box--border` tells me so much more than `o-box o-card`, and I have the ability to remove those arbitrarily. They also tell me theres a relationship between those classes, instead of utility classes all time, code would end up looking like a bunch of utilities instead of something meaningful ... `class="o-box o-card o-card-no-border o-card--shadow u-mb+@bp2"`.

Anway I'm going to try it this way, but I wouldn't hold my breath.

Lastly, I think the list--bare object is styling, your removing the styling from a list, so surely thats also a component?

**Comment by rowild** [comment]
Wouldn't the "o-card o-card--no-border o-card--shadow" be a very specific card and therefore better be a component called e.g. "c-greetingscard" including all those specific stylings?

Components are the place for styling, right?

I have to admit, I am also very confused. Isn't there a showcase anywhere? Could anybody post some links to websites using the new inuitcss?

**Comment by herzinger** [comment]
@rowild you are right. 

The confusion you guys are having here is in understanding a component that uses an object in it. We have no exemples of that situation documented at all. I'll see if I grab something from my current project and adjust it as simple examples. 

But the core of the problem is still lack of understanding of what an object is supposed to be.

**Comment by herzinger** [comment]
@aaronstezycki about the list-bare object: what we avoid is cosmetic styling. Structural CSS is what an object is all about. The old inuit's list-ui was removed for that exact reason, as it introduced design.

**Comment by nenadjelovac** [comment]
@aaronstezycki You might give [this article](http://csswizardry.com/2015/03/can-css-be-too-modular/) from csswizardry a read to see why inuitcss is not part of [expressive](https://www.google.rs/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=expressive%20css) aka [functional](https://blog.colepeters.com/building-and-shipping-functional-css/) aka [composable](https://medium.com/sanctuary-computer-inc/composable-scss-for-the-functional-programmer-5c8a8427904d#.cmsai6sac) css movement. 

Long story short:

>The problem, I think, is that with any new tool or technique we learn, we try and take it to its **fullest extreme**. We then see how that led us slightly astray, and then we begin to correct. Almost any dev problem/solution I’ve ever seen looks like a pendulum: one extreme; extreme overcorrection; finding the sweet spot.

The way I see it, inuitcss way *is* the sweet spot. And, like @herzinger said in [this comment](https://github.com/inuitcss/inuitcss/issues/177#issuecomment-249615565), you have to wrap your head around inuitcss philosophy/mindset. For me, inuitcss and composable/functional/expressive css seem like two (almost diametrically) different school of thoughts. 

So, if I would to judge by your comment here:

>Anway I'm going to try it this way, but I wouldn't hold my breath.

You are not bought on inuitcss idea and *that's ok*. What you're trying to get is more in line with composable css:

>Composable CSS should be your **80–90% solution** to styling your project. For a better codebase, only “dip into CSS” as a last resort. ([source](https://medium.com/sanctuary-computer-inc/composable-scss-for-the-functional-programmer-5c8a8427904d#.cmsai6sac))

With inuitcss you can do *a lot* of styling/layouting with combination of objects, components, and utility classes. You usually "dip into CSS" with `components` layer and add some of your own (or project specific) objects/utilities here and there.

But in inuitcss creating components with combination of utility classes should be **the exception rather than the rule**.

**Comment by herzinger** [comment]
Just to be sure: I showed 2 options of how to solve the problem presented, them mentioned an utility class as a side note (I even have the other two in an ordered list, to further point it). Usually you would only even consider an utility class if it's only one very specific change you want to make to a component or object, in a specific situation.

**Comment by nenadjelovac** [comment]
Just stumbled upon this https://blog.mariano.io/battle-of-the-architectures-30c512d542a4#.p2h246w8d so sharing here as it's related.

**Comment by hayatbiralem** [comment]
Actually __object__ is the first described namespace in [here](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#the-namespaces). 

_P.S. Thanks to @nenadjelovac._

**Comment by nicoqh** [comment]
Regarding objects vs. components, Harry gave an informative answer [here](http://blog.honeypot.io/interview-harry-roberts-css-wizardry/):

> 
> if a user can identify it, it’s probably a component; if it’s private to developers (e.g. your grid system) it’s probably an object. I think the best way to differentiate is like this:
> 
> An object:
> 
> * is purely structural: it only provides structure and scaffolding (e.g. a grid system)
> * has no cosmetics: they can’t have font-sizes, colours, etc. applied to them
> * is ‘invisible’: objects don’t actually look like anything identifiable
> 
> A component:
> * actually looks like a thing: users can usually name components (e.g. a button, a carousel).
> * usually encapsulates a piece of functionality (e.g. a date picker).
> * has (structure and) cosmetics: components introduce colours, font styles, etc.

If the "card" is a recognizable piece of UI that is used throughout your app, there's nothing wrong with having it as a self-containing component, like:

```
.c-card {
    display: block;
    background: #fff;
    border-radius: $global-radius;
}

.c-card__body {
    padding: $inuit-global-spacing-unit;
}
```

In this case I don't bother with the `box` object. I've abstracted cosmetic and structural styles to its own component.

**Comment by herzinger** [comment]
@nicoqh that's a valid approach for simple components, but as they become more complex, incorporating objects will make 'em more DRY.

**Comment by aaronstezycki** [comment]
I guess that leaves the question: Are your going to end up repeating yourself with code? If I created a totally separate component as mentioned above by @nicoqh for most of the objects in the project, what would be the point in using or even @importing the box object if I create a better version of it with my own component. I think @herzinger has nailed it with his response, but I learn in the doing and not so much in the reading, so once I have completed adding my own components and objects I'll end having a good understanding of it. 

However, what lead me to be confused initially are some of the inconsistencies within the frame work. And this allows me to believe or 'make up in my own head' what a object or component should be (without documentation, I know its coming).

Should the following be in the components folder because in a small fashion, they change cosmetics?

List Bare - is a unstyled list, which removes list styles, so surely this is a c-component as it removes cosmetics. (The act of removing a style (in my opinion) is also a cosmetic change).

Inline List - also makes use of removing cosmetics and adds layout, but it also has a modifier class of 'delimited' which could be argued as a cosmetic change because it puts a comma's in-between the list items.

I'm not sure about the o-table object either, as by default tables have cosmetics attributes, i.e. borders.

Anyway, thanks for all contributions here to this discussion, and thanks for links... they have helped! 👍

**Comment by herzinger** [comment]
@aaronstezycki Inuitcss is still in beta, so that kind of feedback is really good to have. I'll try and defend/expand a bit on the points you raised, and at the end I'll try and give a better definition of object and component.

**List Bare** although I get and agree with your point about removing style being styling, I believe this here ia a small enough and common enough pattern to warrant a position as an object instead. 

**Inline List** you are perfectly right here. That's why the delimited modifier was dropped in a recent update and will not be there in version 6.0.0-beta.5. The rest of the object falls in the same category as list bare above. Maybe this could actually be better as a modifier `.o-list-bare--inline {}`.

**Table** That's why it's an object in inuitcss. Most frameworks would incorporate this kind of styling directly on the elements, but we try to be as unoptionated as possible. Actually, It's not rare to see styling similar to `.o-list-bare` dropped directly on `ul li` elements in the wild too. I think this kind of really common elements modifications live comfortably at the objects layer, since it's the lowest classed layer.

---
 Finally, following my early explanations, an object is something you could use as estrutural part of many different components without having to change much - or any - of it's characterists, and is low level and far reaching. Also, in the rare cases you need to make any adjustment, you'd want to be able to overwrite some aspects of it with easy in your component level, so the enforced source order is welcome. It's not that you can't, but it's a LOT less common for a component to be a structural part of another. 

Hope that helps.
