### ISSUE TITLE
Releases schedule

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#188]
Is there any? I mean, for version bumps and package managers updates.

**Comment by anselmh** [comment]
Hi @herzinger, no we don’t have a fix release scheme or even a schedule for a variety of reasons.  
The first and most important one is this project not being a full-time project for anyone of us.  
The second one is that there’s no real value behind pushing a release on a fixed schedule — whenever a feature, bugfix or a new major version is ready, it’ll be published.  
Please understand that you can’t compare inuitcss with a browser like Firefox where publishing a new version every six weeks is of value and doable.
This said, new major versions (such as the one we’re currently working on) are always announced early, there will be pre-releases so that you can participate in discussions and prepare your code if it’s of any use-case to update your project to the newer version.
