### ISSUE TITLE
Which approach for naming inuitcss plugins?

### ISSUE THREAD

**Issue by hayatbiralem** [inuitcss/inuitcss#198]
Hi,

We discussed about `inuit-displays` on #190 in recent days and have released a [plugin](https://github.com/hayatbiralem/inuit-displays) for it.

`inuit-displays` is an utility so I wonder `inuit-u-displays` is it a better name?

I'm curious about it because of that I'm planning to start an inuitcss component plugin then I noticed that `inuit-displays` and `inuit-carousel` looks like each other.

So this naming approach is better, I guess:

### Objects
- `inuit-o-{object-name}`
- `inuit-o-container`

### Components
- `inuit-c-{component-name}`
- `inuit-c-carousel`

### Utilities
- `inuit-u-{utility-name}`
- `inuit-u-displays`

### What are you saying?

This method also provides an easy search trick for plugins on GitHub or Bower like [Harry's side effect](http://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#handy-side-effects).

Do you think this is good or not?
How should we proceed?

**Comment by herzinger** [comment]
The problem is: some plugins - in fact, all of the ones I have in mind right now - use more than one layer. That being said, I wouldn't even use the Inuit prefix, to be honest, since I want them to work fine as standalone pieces of code that can be seamless integrated to inuitcss' structure.

I.e: even if I have to use one of inuitcss' global variables, I would instantiate a version of myself, with a sensible default, and point out in documentation how to predefine it with inuitcss' one, like so:

```scss
$avalon-gutter: $inuit-global-spacing-unit;
```
*Avalon being the name of my layout/widths alternative, that ships with mixins, functions and concerns both objects and utilities.

**Comment by hayatbiralem** [comment]
Thanks to you my thoughts on this matter was clarified a bit more. 👍

**Comment by csshugs** [comment]
@hayatbiralem 
I agree with @herzinger. Naming your plugin `inuit-displays` is just fine.
