### ISSUE TITLE
abstract mixins into the tools layer

### ISSUE THREAD

**Issue by herzinger** [inuitcss/inuitcss#237]
I was trying to write some tests for #236, and at first I wasn't able to. Then I took a look at `utilities.widths` and saw that the tests for that were commented out. After looking at [true's repository](https://github.com/oddbird/true) I discovered that it can't handle files that output code. I commented out every output in the file and was able to make the tests work just fine.

The solution would be to abstract the mixins into the tools layer. Also, as I see it, it's the right thing to do. One more thing: There are some loud comments were they should be silent.

Also again: feature switches and configuration vars should all go in the settings layer, either into `settings.core` or in dedicated partials, like `settings.widths`.

**Comment by csshugs** [comment]
@herzinger 
We once had the files separated but [decided (and are still convinced) to have the settings, the mixin and the utilities in one file](https://github.com/inuitcss/inuitcss/issues/117), because it basically makes no sense to split them into separate files, because no one would ever use the particular parts of that file alone. 

You are right that if we would do it the way you proposed, the tests for the widths module would work, but that's no reason to compromise our code. We need to wait with the test cases for widths until Sass-true is able to handle files which output code.

Thanks very much for working this out, but since the topic of whether we separate or combine the individual parts of the widths module has been decided in #117, I close this.

**Comment by herzinger** [comment]
@csshugs I highly disagree, but okay.
I take it to mean that I don't need to bother with tests for #236 then, right?

**Comment by csshugs** [comment]
@herzinger 
Yeah, since Sass-true seems to lack the appropriate support here, we can't test it, so don't bother.

(...well, unless you got an idea to work around it)

**Comment by herzinger** [comment]
@csshugs Short of forking their project and solving the issue, like what I did it for SassDoc, nothing to do. I'm not even sure they should to be honest, as I strongly believe abstracting those things is the best way to go.
