### ISSUE TITLE
layout object overflow

### ISSUE THREAD

**Issue by snhasani** [inuitcss/inuitcss#241]
I create simple layout:

```
<div class="o-wrapper o-wrapper--small">
    <div class="o-layout">
        <div id='col-1' class="o-layout__item u-1/2"><span>col 1</span></div>
        <div id='col-2' class="o-layout__item u-1/2"><span>col 2</span></div>
    </div>
</div>
<div class="o-wrapper o-wrapper--small">
    <div class="o-layout">
       <div class="o-layout__item"><span>col 1</span></div>
    </div>
</div>
```

But this layout made overflow on x-axis! What is wrong with it? Is my layout is wrong or ...?
You can see this layout in here: http://codepen.io/snhasani/pen/XNREoB

**Comment by nenadjelovac** [comment]
You have tweaked `o-layout` and `o-layout__item` to use right margin/padding and that is causing the overflow.

**Comment by snhasani** [comment]
@nenadjelovac thanks for your respond. Because I develop right-to-left website I flip CSS to rtl with node rtlcss package. But this issue is wired to me. I wrapped all my markup into a simple rtl div like this:

```
<!doctype html>
<html lang="fa">
<head dir="rtl">
</head>
<body>
    <div dir="rtl">
        <div class="o-wrapper o-wrapper--small">
		<div class="o-layout">
			<div id='col-1' class="o-layout__item u-1/2"><span>col 1</span></div>
			<div id='col-2' class="o-layout__item u-1/2"><span>col 2</span></div>
		</div>
	</div>
	<div class="o-wrapper o-wrapper--small">
	    <div class="o-layout">
		<div class="o-layout__item"><span>col 1</span></div>
	    </div>
	</div>
   </div>
</body>
</html>
```

I expect rtl version work too! Can you explain to me why it's not working?

**Comment by nenadjelovac** [comment]
@snhasani  After little bit of googling and landing on [this answer on StackOverflow](http://stackoverflow.com/a/21293594) I think it has to do with the direction in which scrollbar starts scrolling (from left to right instead of reversed order). I've tried adding the proposed solution to your codepen version like this:

```css
body,
html {
  direction: rtl;
}
```

and it seems to fix the issue. Now, I don't what node-rtlcss does to your css, but as I said this fixes the issue on your codepen.

**Comment by snhasani** [comment]
@nenadjelovac I can't add rtl direction to body and html tags, because vertical scrollbar in IE when document direction is rtl its move to right-side of browser window! 😑 

https://gist.github.com/Integralist/7269907#markup

**Comment by nenadjelovac** [comment]
@snhasani I think it's a tricky thing (since it's UX related and scrollbars behave differently in different browsers when using `rtl`) and _you_ have to ultimattely decide what to do about it.

Here are some (opposing) thoughts:
https://www.drupal.org/node/409988
http://stackoverflow.com/questions/1261869/setting-the-correct-orientation-for-scrollbars-in-right-to-left-pages

I would personally go with adding `direction: rtl;` to `html` and `body`, but I might be proven wrong by the users of my site.

**Comment by snhasani** [comment]
@nenadjelovac thanks a lot. I decide add rtl to body and html tag finally, For IE users habits!

**Comment by nenadjelovac** [comment]
@snhasani no problems. Let us know how it goes ;)
