### ISSUE TITLE
Pack object default spacing

### ISSUE THREAD

**Issue by davidbwaters** [inuitcss/inuitcss#249]
Maybe I'm missing something, but why isn't the global spacing applied to the `border-spacing` of the pack object?  I don't see any version of it with the global spacing.  The way I see it, it should be applied by default and an `.o-pack-flush` variant should be added to remove it.

**Comment by hayatbiralem** [comment]
+1

**Comment by hayatbiralem** [comment]
Maybe `.o-pack--default` variant can also be considered instead of default `border-spacing` definition.

**Comment by csshugs** [comment]
As the variant without any spacing is very likely the way `.o-pack` is mostly used, I'm in favor of leaving the `.o-pack` class as is, without adding any `border-spacing`.

But @davidbwaters has rightly pointed out, that at the moment there is no variant with a spacing of `$inuit-global-spacing-unit`. So we need to provide an additional modifier class for that.

@davidbwaters, @hayatbiralem, @inuitcss/core 
Any suggestions for a proper class name? `.o-pack--default`, `.o-pack--normal`?

**Comment by nenadjelovac** [comment]
@csshugs I am not sure. I don't use `object.pack`. When I did, I used just `o-pack` without the modifiers (as I needed equal widths items, eg. for tab navigation). 

But nowadays I usually do it via flexbox on component level (still haven't made an object from it).

Anyways, if there is need for spaces between `o-pack__items` I'd vote for `o-pack--default`.

Btw, @davidbwaters @hayatbiralem can you give us an example of design patterns where you're using object pack? Because the only one I needed was tabs navigation, and can seem to come up with any more now.

**Comment by davidbwaters** [comment]
Either way, `o-pack--default` works for me.  I was attempting to use it in place of `o-layout` because I wanted equal height cells when I noticed this.

**Comment by csshugs** [comment]
@davidbwaters 
> I was attempting to use it in place of o-layout because I wanted equal height cells when I noticed this.

Have a look at [this](http://codepen.io/csshugs/pen/OVovvo).

**Comment by csshugs** [comment]
#263 is merged.

Thanks @davidbwaters for pointing this issue out!
