### ISSUE TITLE
Responsive hide

### ISSUE THREAD

**Issue by davidbwaters** [inuitcss/inuitcss#250]
Hi, if things like responsive spacing is being added, i feel something like this addition I use is inevitable:

```
@if (variable-exists(mq-breakpoints)) {

  @each $inuit-bp-name, $inuit-bp-value in $mq-breakpoints {

    @include mq($from: $inuit-bp-name) {

      .u-hidden-from#{$inuit-widths-breakpoint-separator}#{$inuit-bp-name} {
        display: none !important;
      }

    }

    @include mq($until: $inuit-bp-name) {

      .u-hidden-until#{$inuit-widths-breakpoint-separator}#{$inuit-bp-name} {
        display: none !important;
      }

    }

  }

}
```

**Comment by SarokuTuli** [comment]
A similar concept should be used for spacing utilities too.
I often need to have different margins with different breakpoints and I created my own mixin for those.

**Comment by herzinger** [comment]
That's the third or forth different concept for the same thing suggested here, all shoot down. I think it's pretty obvious that there is a demand for that.

**Comment by clindsey** [comment]
here are the previous issues I could find about this -
https://github.com/inuitcss/inuitcss/issues/190
https://github.com/inuitcss/inuitcss/issues/175
https://github.com/inuitcss/inuitcss/issues/173
https://github.com/inuitcss/inuitcss/issues/165

**Comment by csshugs** [comment]
We know that there is a strong demand for a responsive hide utility. 
But as [already stated here](https://github.com/inuitcss/inuitcss/issues/190#issuecomment-253725700), there are a few unpredictabilities we have to be aware of. We don't want to provide a half-ready solution, so this will not go in version 6.0.0.

Be all assured that we have this on our list and we will offer a solution in a future release of inuitcss, but until then you have to either write it your own (e.g. as shown at the top of this issue) or use the [awesome plugin](https://github.com/hayatbiralem/inuit-displays) @hayatbiralem has already published.

We are very sorry to disappoint you in this topic, but our priority is getting inuitcss out of beta towards version 6.0.0. Therefore we are concentrating on shaping everything to its perfection, but are not adding new modules for 6.0.0 in order to get inuitcss out of beta.
