### ISSUE TITLE
Utility / Trumps

### ISSUE THREAD

**Issue by denu5** [inuitcss/inuitcss#255]
maybe I cant find it, but I'm missing some utility classes for positioning and some basic text utilitites.

text:
1. u-text--center, u-text--justify u-text--left/right, u-text--truncate

position:
something like in bootstrap: u-pull-left, u-pull-right.
maybe classes for fixed positioning.

have these topics already been discussed and rejected or shall i try to do a pull request :) ?

regards,
robert

**Comment by csshugs** [comment]
@denu5 
We don't want inuitcss to become a utility class library. inuitcss aims to be very unopinionated concerning the modules it provides in its core. 

So, for now we will not incorporate such utilities, but they are definitely worth considering to be published as inuitcss plugins such as [this one](https://github.com/csshugs/trumps.helper.text-align).

Thanks for bringing this up, though!

---

By the way: I'd recommend reconsidering the naming of those classes, if you write them yourself. Because they all technically are no BEM modifiers, I'd rather write them as follows:

```scss
.u-text-center {
  ...
}

.u-text-justify {
  ...
}

etc.
```

i.e. without the double-dash.

**Comment by nenadjelovac** [comment]
Hey @denu5,

@csshugs beat me to it with his great answer/suggestions ;)

One thing he missed though:

>something like in bootstrap: u-pull-left, u-pull-right.

Inuitcss does have that - in the `utilities.widths.scss` (check [these lines](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss#L51-L59)). Since pull/push classes are optional you should turn it on when you need them.

Hope this helps.

**Comment by denu5** [comment]
@csshugs thanks for your answer and remarks.
@nenadjelovac thats not exactly what i was looking for, In my projects I am using something like:
`
/**
 * Float elements left or right
 */
.o-pull{
  @include inuit-clearfix();
}

  .o-pull__item-left{
    float:left;
  }
  .o-pull__item-right {
    float: right;
  }

`

Does this make sense?

**Comment by nenadjelovac** [comment]
@denu5 I see what you're trying to do. Here's what I usually do for that:

```html
<div class="u-clearfix">
  <div class="u-float-left"></div>
  <div class="u-float-right"></div>
</div>
```

U clearfix is something we already [have in inuit](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.clearfix.scss), and float classes are something I add to my projects in utilities layer. eg:

```css
.u-float-left {
    float: left !important;
}

.u-float-right {
    float: right !important;
}
```
