### ISSUE TITLE
naming or extending Inuit with own classes

### ISSUE THREAD

**Issue by denu5** [inuitcss/inuitcss#258]
One more question for today. Is there a recommended way how to structure your own code within inuitcss? I have read in the readme the section about extending with <section>.<file> but wouldn't it be "more standalone" to copy the root folder structure and place in the root as "myextenstion" - so it would be easier to update inuit for example.

I understand the not opinionated ideology of inuit, but sometimes it might be useful to guide especially less experienced developers into the right direction. 

Best Regards
Robert

**Comment by csshugs** [comment]
@denu5 

> but wouldn't it be "more standalone" to copy the root folder structure and place in the root as "myextenstion" - so it would be easier to update inuit for example.

I'm not sure I understand correctly. Can you please give a concrete example of how the directory structure would look like, when doing so?

> I understand the not opinionated ideology of inuit, but sometimes it might be useful to guide especially less experienced developers into the right direction.

Can you elaborate a bit more? What do you mean by that?

**Comment by denu5** [comment]
Well, I am not sure how I should/must use inuitcss as a repository. Shall I leave it in node_modules, and take out the main.scss and put that in my css project folder? ->As I am writing this, I this is perfectly explained in the readme haha... 

So to sum up, I probably should have the same inuitcss folder structure in my project scss folder, so things stay consistent. Maybe it woud be "idiotensicher", if there would be an empty folder structure which one can copy from the npm folder :)

You can feel free to delete this issue

**Comment by csshugs** [comment]
@denu5 
> Shall I leave it in node_modules, and take out the main.scss and put that in my css project folder?

Exactly. The important thing is to always keep inuitcss from your own code separated completely. That's why it stays in `node_modules`. That also makes sure you can always safely update the framework. 

> [...] an empty folder structure which one can copy from the npm folder

Our point always was—and still is—that this is something you need to do on your own. The one downside of this modularized, unopinionated approach of inuitcss is that you need to build it all up in your project yourself. What I do and what I've seen/heard of many other inuitcss users do is creating their own kind of inuitcss-boilerplate they can use in every new project.

> idiotensicher

😆
