### ISSUE TITLE
Does bower need a version bump?

### ISSUE THREAD

**Issue by aaronstezycki** [inuitcss/inuitcss#270]
Downloading via Bower gives you some older files, like the tools/rem.scss, and hasn't got some of the more recent changes to the styles.

Am I downloading it wrong, or is it Inuits end?

**Comment by herzinger** [comment]
Look at the version number you have. The latest release is `6.0.0-beta.4`. The main branch here (develop) is ahead of it, since it have some unreleased stuff.

**Comment by csshugs** [comment]
@aaronstezycki 
The state you see on GitHub is always the most current **development** version. The versions that you download via bower or npm is versioned with [git tags](https://github.com/inuitcss/inuitcss/tags). And since the latest version is [6.0.0-beta.4](https://github.com/inuitcss/inuitcss/blob/126bebe2ff2146b7101ef28fb1b2c0c4832261dc/bower.json#L3) which is from 2016/10/18, it's rather "old" compared to the current development version.

You can see [in the milestones section](https://github.com/inuitcss/inuitcss/milestone/3) when we will release the next version.

So it wasn't your fault, but if you really need to have the latest development version, you can get it with:

```
$ bower install https://github.com/inuitcss/inuitcss.git#develop
```

or in your `bower.json`:

```json
"dependencies": {
    "inuitcss": "git@github.com:inuitcss/inuitcss.git#develop"
}
```

But I wouldn't recommend that for a real-life project, because since it references the development branch and you update/install the bower dependencies at the wrong moment, it could break your code. But for tinkering around with inuitcss, you can totally do that.

**Comment by aaronstezycki** [comment]
@csshugs Hi thanks!

Okay just took a look at the milestones needed for .5. Perhaps we need a 'bump' for the project, as it seems to have gone a little quiet as of late. I'm a little concerned that lack of progression will likely result in the project gaining no traction, and it just being left just like previous versions.

I've put in quite a lot of effort into maintaining my current project with Inuit and would love to see a proper v1 released, rather than the project stagnate in a beta circle.

Having said that, great work from the team so far :)

**Comment by herzinger** [comment]
@aaronstezycki it will be v6 after getting out of beta, not v1.

**Comment by aaronstezycki** [comment]
@herzinger, Okay. thanks for that nugget of special info. 😂 I've used inuit since v2.

I meant it would be nice, to have a full release and final version (which in software release cycle terms usually means v1 or production release, its currently in beta). Generally when you have a project in alpha/beta they are not production worthy. This project has perpetually stagnated in alpha, beta and in previous versions ie. v1, upto v6. So my point is, lets get a full release out! So people can get using it properly in their projects.

**Comment by herzinger** [comment]
Each full version has it's own lifecycle. The production release for `v6.0.0-beta.x` is `v6.0.0`.
