### ISSUE TITLE
ratio class output fails

### ISSUE THREAD

**Issue by davidhellmann** [inuitcss/inuitcss#275]
Hey,

the ratio classes like o-ratio--16:9 are not possible. He made 16\:9
`.o-ratio--#{$antecedent}\:#{$consequent}::before`
Here is the Sassmeister Gist: http://www.sassmeister.com/gist/b24fc0264955c3277b2a74eb7bba4a4d

Just saying. I changed it to `.o-ratio--#{$antecedent}-#{$consequent}::before`

**Comment by csshugs** [comment]
@davidhellmann 
The Sassmeister Gist you posted outputs me the following:

```css
.o-ratio--16\:9::before {
  padding-bottom: 56.25%;
}
```

And that's exactly what we want.

Or do I misunderstand your issue?

**Comment by nenadjelovac** [comment]
@davidhellmann I've used it on a few projects and it does work. [Here's an example](http://codepen.io/anon/pen/RKzMKr) on codepen. I used your exact code and just added html example (I couldn't get it to work on Sassmeister for some reason).

**Comment by florianbouvot** [comment]
@davidhellmann I use it on every project *(to keep video or image ratio and take space for lazy loaded content)* and I think it work pretty well.

We choose to use `:` delimiter so escaping it necessary but ratio are ok, can you give us more info?

**Comment by herzinger** [comment]
If I understood the issue, it's just about the scaping. There's nothing wrong with it.

**Comment by anselmh** [comment]
Since there’s no further confirmation or additional details on what actually does not work, and this [JSBin](https://jsbin.com/zehuvugeku/edit?html,css,output) that I just created to determine if our code is working, I’m going to close this.

@davidhellmann if you provide any more details on what’s not working as expected, please let us know so we may help you or re-open the ticket.
