### ISSUE TITLE
why is _utilities.print.scss a utility?

### ISSUE THREAD

**Issue by area73** [inuitcss/inuitcss#286]
Hi,
looking at _utilities.print.scss I can't imagine why the media print is set into utilities layer and not on generic layer.

Thanks

**Comment by csshugs** [comment]
Yeah, the prints utility is kind of an exception in being a utility. But it has to be a utility, because it overrides [elements](https://github.com/inuitcss/inuitcss/blob/28c383a08f4284fdc76d796a75ab1ab8068638db/utilities/_utilities.print.scss#L53-L57)-[level](https://github.com/inuitcss/inuitcss/blob/28c383a08f4284fdc76d796a75ab1ab8068638db/utilities/_utilities.print.scss#L64-L66) [stuff](https://github.com/inuitcss/inuitcss/blob/28c383a08f4284fdc76d796a75ab1ab8068638db/utilities/_utilities.print.scss#L78-L83) for the print-specific styles. If this would be included in the generic layer, i.e. _before_ the elements layer, some print-specific declarations might be overridden in the elements layer subsequently by accident.

ITCSS-wise, it's not 100% correct and seems a bit inelegant, but it's **safe and pragmatic** to put this in the utilities layer.

**Comment by area73** [comment]
No I got it :) thanks

**Comment by nenadjelovac** [comment]
@area73 

>ITCSS-wise, it's not 100% correct and seems a bit inelegant, but it's safe and pragmatic to put this in the utilities layer.

This pretty much sums it up, but you can read a bit more about the thought process that lead us to leaving print in the utilities layer [here](https://github.com/inuitcss/inuitcss/issues/100).

**Comment by florianbouvot** [comment]
@area73 can we close this issue ?

**Comment by csshugs** [comment]
Yes :)
