### ISSUE TITLE
@import order for vendor css files?

### ISSUE THREAD

**Issue by ooloth** [inuitcss/inuitcss#292]
Love this project! Just wondering where vendor css files fit into the ITCSS @import order. 

For example, if I'm using a vendor plugin (e.g. slick.js) with its own css file (e.g. slick.css), where do I @import 'slick.css' in my main.scss file? After settings? With components?

I want to respect the ITCSS specificity graph, but some of these vendor libraries don't, so I'm not quite sure where to include them.

**Comment by florianbouvot** [comment]
@ooloth in my case, I add a plugins level between components and utilities.

@inuitcss/core what about you ?

**Comment by rowild** [comment]
I like to put them as late as possible, just for the reason to have utility-classes already declared in case I need them in the markup of a vendor component (in my case that would be jplayer, e.g.). It just helps my thinking to "have everything prepared with inuitcss".
But not all vendor scripts belong there. If you decide to use the latest normalize.css (or sanitize.css instead of normalize.css, e.g.), inclusion must happen way earlier. Same thing with fonts (font-awesome, e.g.).

**Comment by herzinger** [comment]
As said, usually making a component is good enough, but some stuff would go better in other levels. It's something you have to decide for yourself for each case.

**Comment by ooloth** [comment]
Thanks very much for these comments! I guess there's no one location that always makes sense. 

In general, I'll go with placing non-global libraries (like slick) in the components layer and add any global libraries (like normalize or font awesome) in an earlier layer.

**Comment by florianbouvot** [comment]
@ooloth can we close this issue ?

**Comment by ooloth** [comment]
Yup!
