### ISSUE TITLE
[objects.crop] Add more positioning modifiers

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#298]
Current object doesn't include modifiers for `center top`, `center bottom`, `left center`, `right center` positioning. 

We can add it using one of the following approach:

1. `background-position` property approach:

```
.o-crop__content--left-top { ... } // Default
.o-crop__content--left-center { ... }
.o-crop__content--left-bottom { ... }

.o-crop__content--center-top { ... }
.o-crop__content--center-center { ... }
.o-crop__content--center-bottom { ... }

.o-crop__content--right-top { ... }
.o-crop__content--right-center { ... }
.o-crop__content--right-bottom { ... }
```

2. Composable approach:

```
// Default
//.o-crop__content--top { ... }
//.o-crop__content--left { ... }

.o-crop__content--middle { ... }
.o-crop__content--bottom { ... }
.o-crop__content--center { ... }
.o-crop__content--right { ... }

.o-crop__content--centered { ... }
```

Do you think this is useful? (Which approach you consider the best?)

**Comment by herzinger** [comment]
I do like it and I'd go with the second approach

**Comment by nenadjelovac** [comment]
Having seen this implemented in https://github.com/inuitcss/inuitcss/pull/344, and giving it some more thoughts I think `background-position` property approach would be better. 

- The class names are more clear: there's no `o-crop__content--center` vs `o-crop__content--centered` confusion, nor `middle` vs `center`.
- They do one thing (and one thing only) - which makes understanding and readability of html easier.
- And I think it's more easier to grasp the concept since it is based on `background-position` concept.

@inuitcss/core @herzinger thoughts?

**Comment by csshugs** [comment]
@nenadjelovac 
I was unsure, too.

> They do one thing (and one thing only) - which makes understanding and readability of html easier.

This one convinced me. I'm gonna change the PR accordingly.

**Comment by csshugs** [comment]
#344 is merged.

**Comment by herzinger** [comment]
I still like the other approach better, and was never unsure or confused, but it's just a matter of preference, either is fine.
