### ISSUE TITLE
.o-wrapper width vs padding

### ISSUE THREAD

**Issue by danwhite85** [inuitcss/inuitcss#299]
I would like to see the modifiers on .o-wrapper set max-widths instead of left/right padding. Using paddings makes the modifiers useless on mobile. For example, o-wrapper--huge squeezes the content to a thin ~80px container on small screens.

**Comment by florianbouvot** [comment]
@danwhite85 you're right current modifiers aren't very suitable on small screens. 
I think modifiers set left/right padding instead of max-widths to follow others objects approach.

I propose to remove modifiers to keep a simple object. Then inuitcss's users can extend this object with specific needs, for e.g.:

```
// objects.wrapper at project level

// load inuitcss wrapper object
@import "path-to-inuitcss/objects/objects.wrapper";

.o-wrapper {
  @include mq($until: tablet) {
    padding-left: $inuit-global-spacing-unit-small;
    padding-right: $inuit-global-spacing-unit-small;
  }
}

.o-wrapper--small {
  max-width: 33rem;
}
...
```

Thoughts ?

**Comment by zomars** [comment]
I agree completely with this. Also, this topic has been discussed previously in #93.

**Comment by herzinger** [comment]
I don't see any reason to change this. The only thing that should be done is making it responsible. This is something I use in every project, and it makes sense to use gutters equivalent to our spacing. Just make it so we can change the modifier based on breakpoints.

**Comment by florianbouvot** [comment]
@herzinger thank you, It joins what @csswizardry said and I'm beginning to understand 😉

**Comment by nicoqh** [comment]
I usually create max-width utilities and don't use the size modifiers on the `o-wrapper` object:

```sass
$max-width-sizes: (
    22,
    32,
    42
) !default;

@each $width in $max-width-sizes {
    .u-max-width-#{$width} {
        max-width: #{$width}rem;
    }
}
```

```html
<div class="o-wrapper u-max-width-32"></div>
```

I also have modifiers that remove the padding on different device widths, like `.o-wrapper--flush@md`.

Did I get this from you, @herzinger? Or do you do something different?

**Comment by solleer** [comment]
What if you add a modifier like `o-wrapper--width-small` which would be a width modifier and have `o-wrapper--small` stay what it is.

**Comment by florianbouvot** [comment]
@solleer thank you for the suggestion, I think we need to stay with current modifier and everyone can extend this object at project level.

**Comment by zomars** [comment]
Just my two cents but I usually generate modifiers this naming convention to prevent conflict: `.o-wrapper--narrower`, `.o-wrapper--narrowest`, `.o-wrapper--wider` and `.o-wrapper--widest`.

**Comment by herzinger** [comment]
Sorry for the delay.

I personally don't use anything of the sort. In most projects I use only one `max-width`, which is the real, absolute max width of the site, in the larger breakpoints. It varies with the design, but for the sake of exemplifying let's say something like '1200px'. 

For anything else, I work with paddings, and I do that the way I mentioned above, by using the spacing utilities. I normally would code my own responsive utilities, but now we have them built into the framework, so that works just fine.

Of course, that means I don't use the modifiers for the wrapper object at all. We could "fix" that by making the modifiers responsive. Something like `<div class"o-wrapper--large@desk o-wrapper--small@mobile">`, but that's a matter of preference. I think the easiest way is to simply remove the modifiers and use the utilities instead, and if the developer for any reason prefers to work with max-widths (I see absolutely no reason, but...), they can work their own custom modifiers, since it's heavily project based.

**Comment by aaronstezycki** [comment]
@herzinger Love hipster naming.

**Comment by csshugs** [comment]
> I propose to remove modifiers to keep a simple object. Then inuitcss's users can extend this object with specific needs [...]

I'm with @florianbouvot here and think we should get rid of all modifiers, since the discussion in this thread already proves me that everybody seems to have a different way of approaching and extending this object. So staying defensive and unopinionated is a more pragmatic way, IMO.

**Comment by nenadjelovac** [comment]
@csshugs I agree with removing the modifiers. cc @florianbouvot

**Comment by csshugs** [comment]
#340 is merged, so closing this.
