### ISSUE TITLE
Is .o-flag--top actually .o-media?

### ISSUE THREAD

**Issue by afontcu** [inuitcss/inuitcss#300]
Hi!

I was just playing around with Objects and I noticed that, in essence, an `.o-flag.o-flag--top` element is actually just a `.o-media` and then I wondered if it's really necessary to allow the Flag Object to align top.

Since Inuit doesn't allow the Media Object to vertically align top (which makes sense), maybe it would make sense to remove this modifier. Although there might be some other differences which I didn't notice.

Thank you very much for all your work :)

**Comment by florianbouvot** [comment]
@afontcu the flag object is very similar to media object but with the ability to vertically align its content. For more detail, you can read [The flag object by @csswizardry](https://csswizardry.com/2013/05/the-flag-object/).

Then it depends on the needs of your project:

* Image + text: the media object
* Image + texte + vertical alignement: the flag object

The `o-flag--top` modifier is useful because it avoids changing objects...

In the future we will probably make only one object...

**Comment by florianbouvot** [comment]
@afontcu does that answer your question ? If yes can we close this issue ?

**Comment by afontcu** [comment]
@florianbouvot yes, feel free :) just wanted to make sure I wasn't missing something when styling "medias" using "flags". 

Thanks!
