### ISSUE TITLE
offsets: disable in example settings

### ISSUE THREAD

**Issue by fuhlig** [inuitcss/inuitcss#318]
The _manifest_ example sets $inuit-offsets to true but should be removed in my opinion. Why?
- Despite having it in the *example* file this should be removed (default is false) as I guess the manifest serves as a starting point for most
- it generates a lot of lines to due loops (breakpoints & widths)

https://github.com/inuitcss/inuitcss/blob/d84cb4762c945714f4440af6a3db48bce85a4cf6/example.main.scss#L148

(probably an accidental left-over from adding the feature-flag in https://github.com/inuitcss/inuitcss/commit/72781f2e424e7713f88d3d876db1066627d26d98)

**Comment by csshugs** [comment]
@fuhlig The intention of adding it to the the example file is to show the availability of push/pull to the inuitcss user, who might oversee their existence otherwise in the first place. But I'm not sure, why we set it to `true` back then. [We could leave the switch there, but set it to `false` initially](https://github.com/inuitcss/inuitcss/issues/104#issuecomment-238223361), alongside with a CSS comment, indicating the danger of producing a large amount of generated CSS.

```scss
// UTILITIES
@import "utilities/utilities.clearfix";

// Be aware that setting this to `true` produces a large chunk 
// of classes which might bloat your CSS, depending of the amount
// of breakpoints you declared. 
// Only set this to `true`, if you are absolutely sure about what you are doing.
$inuit-offsets: false;
@import "utilities/utilities.widths";
```

(cc @inuitcss/core)

**Comment by nenadjelovac** [comment]
@fuhlig @csshugs I use my own boilerplate (and so do all of the devs I know that are using inuitcss), so I don't have this variable in there, nor have I noticed this as an issue.

>I guess the manifest serves as a starting point for most

In my experience, as said above, that is not the case. My guess would be that the starting point is a custom version of `main.scss` that people have in their starter kit. But I agree that devs that are _first getting to know inuitcss_ can find this confusing, so I think adding the comment (without setting the variable to `false`) would be fine. I mean, if someone is using the `example.main.scss` as a starting point then he should remove the variable and the comment, since it's `false` initially.

@csshugs 
>But I'm not sure, why we set it to true back then. 

I think the reason for setting it to true was to show an example of how to override the default settings of a variable from an utility file. And the reason for choosing `$inuit-offsets` was that it's one of the simplest of all variables we have in utility files (we have a lot of maps in other files). We could have gone with `$inuit-fractions: 1 2 3;` (for example), but then people might not notice that `$inuit-offsets` exist :)

**Comment by csshugs** [comment]
#324 is merged. Closing this.
