### ISSUE TITLE
Help needed: c-btn does not look equal on <button> and <a>

### ISSUE THREAD

**Issue by rowild** [inuitcss/inuitcss#319]
Since I work with inuitcss, I would like to ask you guys here for tips and hints, even though it is not a inuitcss specific problem.

I prepared a pen:
https://codepen.io/rowild/pen/MvLZwL

Here, a "c-btn" and a "c-btn--circle" class are put on a button and an anchor element.
A second set of button and anchor includes a font-awesome chevron.
The basic formatting is taken from inuitcss's button component example. 
The intention is to create a circled click element that looks the same on either DOM element.

The pen shows that the formatting is different on different DOM elements. The containing text of the <a> element is aligned to the top, while the text within the button element is perfectly centered vertically.

As long as the button contains only one word (or a font-awesome icon), the problem can be solved with a line-height attribute of 2.75 (even though I have no idea why it must be 2.75 for 16px, 1.75 for 26px, etc... could not figure out the relation between those values). This, of course, quickly turn into a problem as soon as the button text has more lines...

(It furthermore turns out that a box-sizing and a padding is required to make the circle round.)

So: even though I did not find any different formattings of the anchor tag in comparison with the button tag, the handling of the nested text is not the same, as long as line-height, box-sizing and padding are not added. The button element centers the text automatically, while the anchor tag keeps the text to it top. 

Can anybody explain to me, why this is happening?
And, if inuitcss's intend is to create classes that, no matter to which DOM element they are attached, form the same look and feel, does it really respect all the required parameters to fulfill this expectation (given I did not misunderstand this intention...)?

Thank you for your feedback!

**Comment by herzinger** [comment]
Most types of form elements have special styling, explicit or otherwise, applied by the browser, to achieve their special appearance and/or functionality. That includes buttons, the different types of input and selects. That makes it tricky to hack those elements, of to make anything else behave like then. That being said, you can achieve what you're looking for - without extra markup - by using flexbox, by adding:

```css
display: inline-flex;
align-items: center;
justify-content: center;
```
1. Check for [support](http://caniuse.com/flexbox)
2. Using some sort of autoprefixer helps a lot

`.c-button` is just an exemple component, not part of the framework per se. The current code works for what it's supposed to work, so there's no reason to change. Feel free to add such a solution or anything else to yous version of the component.

**Comment by rowild** [comment]
@herzinger Thank you for clarifying! It makes, of course, much sense to use flex styling, it is just not the first thing that comes to mind, when using inuitcss :-)

**Comment by herzinger** [comment]
Inuitcss is, at the end of the day, just CSS. You can use whatever features you need on your project. Can this issue be closed?

**Comment by rowild** [comment]
Yes, sure, can be closed! Thanks!
