### ISSUE TITLE
Crop and Ratio seem to achieve the same thing

### ISSUE THREAD

**Issue by ghost** [inuitcss/inuitcss#363]
the .o-crop and .o-ratio objects seem to achieve the same thing, I'm struggling to see the need for both.

**Comment by herzinger** [comment]
Look again. Ratio modifies the element it's applied to, crop its boundaries. I do agree they are similar, but each is better for some uses than the other. Personally, I have a mixin to do the same, with a parameter to modify it's output between the two modes instead of having 2 separated objects, but there's nothing wrong with the way inuitcss does it. Remember: this is a modular framework. If your project just needs one of the two, simply don't import the other.

**Comment by ghost** [comment]
Thanks for the reply, makes sense. Closing.
