### ISSUE TITLE
[utilities.spacings] Question about the spacing size

### ISSUE THREAD

**Issue by patrykbialek** [inuitcss/inuitcss#366]
Question....

We have utility size like 'small', 'tiny', etc. Why it's not presented as modifier?

So instead of `u-margin-top-large` should be `u-margin-top--large`.
Any reason?

**Comment by csshugs** [comment]
A modifier does, as the name suggests, **modify** an already existing class. It enhances or adds something that the base class already brings with it. 

For example: We have our [`.o-box` object](https://github.com/inuitcss/inuitcss/blob/7284ae4802a48ed6546041f9f4df32cbda16b03b/objects/_objects.box.scss) that basically just adds padding to an element. We can **modify** the behaviour of that element with e.g. the `.o-box--small` modifier, so we get a smaller padding. However, we need both classes (`.o-box  .o-box--small`) on the element since `.o-box--small` just **modifies** the base class (it does not replace it!).

The spacing utility classes however **do not modify** any base classes. Since these are utility classes, each of these just do one thing only. It wouldn’t make any sense to provide some kind of base spacing class and override all the spacings each time with the individual spacing modifiers. 

A modifier has a dependency on its base class. A utility class does not have any dependencies.

**Comment by patrykbialek** [comment]
Hi, yes... clear now. Thanks for explanation.
