### ISSUE TITLE
Follow 8 point grid for baseline and vertical rhythm

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#395]
There are a lot of articles about 8 point grid system and company using it. I think it can be a "better" default for inuitcss too.

- [Intro to The 8-Point Grid System](https://builttoadapt.io/intro-to-the-8-point-grid-system-d2573cde8632)
- [8-Point Grid: Typography On The Web](https://medium.freecodecamp.org/8-point-grid-typography-on-the-web-be5dc97db6bc)

Agree ?

**Comment by florianbouvot** [comment]
If everyone agrees, we use 8, 16, 24, 48 and 96px or others ?

_On some project I use 8, 16, 32, 64px, I like it even if it does not correspond to line height 😅_

**Comment by herzinger** [comment]
We use a 8, 16, 24, 48 and 96px baseline at my job, by the original designer's choice, but I personally prefer the 6 based one we currently have in inuitcss. The articles you linked defend the 8px one in favor of none, and as I said we already have a pretty good one. Can you point me any advantages of 8px over 6px?

**Comment by LayZeeDK** [comment]
`$inuit-global-baseline` is already configurable, so what is the point?

**Comment by florianbouvot** [comment]
@herzinger I don't know if there are real advantage, multiples looks better:

- 32, 64, 128... works and are common/useful number (icon, ...)
- 16 correspond to default browser font size

@LayZeeDK right but I'm thinking 8 is a better default so I want to talk about that.

**Comment by kkalvaa** [comment]
Late to the discussion here, but: I do not think inuit.css should be fixed on one predefined baseline grid over another, especially when the baseline already is configurable.

Baseline grid is an old typographic principle, same with vertical rhythm. Having them is a GOOD thing in your design as it make everything more harmonious, however: no designer ever have enjoyed getting locked in to one predefined rhythm because someone on the internet thought the maths were nice with X rather than Y.

One of the reasons Elliot Dahl in the linked Medium post list is because 8 is divisible by the majority of popular screen sizes, something which is completely counter to responsive design where the size of the screen doesn't matter.

**Comment by herzinger** [comment]
Making it fixed was never part of this discussion. When I introduced the current vertical flow system a while back, with the font-size and settings core refactoring, I made sure to make it easy to change, with the baseline factor and multipliers variables. As I said before, in the long running project I work with at my job, I myself use a different scale following a design decision.

That being said, I don't see any major advantage to a 8px based scale over 6px as a default, seeing it as a per project decision anyway, much like the 3, 5, 12, 16 columns grid decision (which is also completely configurable in inuitcss).

With that in mind, I don't really see a reason to introduce such change, as it would be pretty much a breaking chance: it would modify all spacings of existing projects conforming to the default factor, requiring extra code to fix.

**Comment by ajshortt** [comment]
I do feel that as it is customisable then this isn't really an issue as all projects are different. I do, however, agree that 8px is the most popular within designers, and has its benefits over a 6px or 10px.

Firstly, 8px is the most divisible out of the three baselines on the most popular device sizes. I've extended a diagram and added the 6px to illustrate.

![baseline-resolution-table](https://user-images.githubusercontent.com/6783995/51841035-8b46ea80-2305-11e9-9ddf-1134106b3435.jpg)

Secondly, scaling a 6px would mean more variables for larger sizes whilst a 10px scale doesn't offer as much definition. 8px is perfect in this case.

Finally, 8px fits into the default 16px font size in terms of `rem`s too.

So I completely agree, it's configurable but I must defend designers and others that 8px is the most popular because of several reasons

**Comment by herzinger** [comment]
The divisibility of screen sizes is just a math factoid. It doesn't matter at all, even if you ignore the fact you shouldn't really design for specific screen sizes, as one of the main principles of responsive design. To begin with, your workspace is defined by the browser, not the screen, so your baseline is not garanted to align with the "fold" no matter what. The same goes for the font size: it doesn't matter. Font-size is not what defines the baseline, white space is. About needing more variables for larger sizes (which I'm interpreting as "larger spacings"), that's wrong: you'll need either different multipliers or smaller white space areas. Too much variation in spacing sizes affects consistency, one of the main reasons to follow a baseline in the first place. In short: it's 100% a design decision.

To illustrate it better, there's nothing particularly special in a 6px based scale either, other than it being an even, small enough number, same as 8px, arguably same as 10px. The only reason I used it when design the current default is that it was the default used by @csswizardry since the original font-size, grid system and later adopted by inuitcss in general.

The reason I'm against the change is not because I don't like a 8px baseline, it's because the default is irrelevant and the change unnessessary.

**Comment by csshugs** [comment]
> [...] the default is irrelevant and the change unnessessary.

I agree and close this issue.
