### ISSUE TITLE
Objects to port over from inuitcss 6.0.0-alpha

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#40]
We need to start porting over some existing Objects from the current inuitcss.

I think these ones are pretty core:

- [x]  [`objects.media`](https://github.com/inuitcss/objects.media)
- [x]  [`objects.box`](https://github.com/inuitcss/objects.box)
- [x]  [`objects.flag`](https://github.com/inuitcss/objects.flag)
- [x]  [`objects.list-inline`](https://github.com/inuitcss/objects.list-inline)

Less obvious:

- [x] [`objects.pack`](https://github.com/inuitcss/objects.pack) – could flexbox replace this (what about oldIE?)?
- [x] [`objects.block`](https://github.com/inuitcss/objects.block) – possibly useful, but too specific?
- [ ] [`objects.tabs`](https://github.com/inuitcss/objects.tabs) – possibly useful, but too specific?
- [ ] [`objects.list-block`](https://github.com/inuitcss/objects.list-block) – possibly useful, but too specific?
- [ ] [`objects.list-ui`](https://github.com/inuitcss/objects.list-ui) – introducing design?

**Comment by florianbouvot** [comment]
@csswizardry I switch list to checklist in your first comment, hope it improve understanding.

**Comment by mhauken** [comment]
Some objects i always use (apart from the core):

### objects.buttons
I understand this is going over to an [example of component](https://github.com/inuitcss/inuitcss/blob/develop/components/_example.components.buttons.scss)?

### objects.list-ui
I can agree that this introduces a bit design, and that I often modify them quite a bit. But could this also be added as an example like objects.buttons?

Regarding @florianbouvot comment:
> Sometimes we only need border between o-list-ui__item, is there a way to support this use case easily ?

I use something like this:
```
.o-list-ui--open {
  border-top-width: 0;

  .o-list-ui__item:last-child {
    border-bottom-width: 0;
  }
}
```

**Comment by csshugs** [comment]
@mhauken 

> I understand this is going over to an example of component?

Yes.

> But could this also be added as an example like objects.buttons?

I think one example for the components layer is sufficient for now. 

Apart from that, just like you said (what a lovely rhyme eh :)): `objects.list-ui` would introduce design bits, so this does not fit into the object layer.

---

What does @inuitcss/core think? Do we need any more objects? The ones missing at the moment from the proposed list are:
* `objects.tabs` - we have `objects.pack`, so this one would be redundant, right?
* `objects.list-ui` - as being said: introduces cosmetics
* `objects.list-block` - too specific

Any other wishes for new objects to introduce? Otherwise we could declare the discussion around the objects layer to be completed.

**Comment by nenadjelovac** [comment]
@csshugs I'm good with what we have now, so I wouldn't add the missing three. #myTwocents :)

**Comment by csshugs** [comment]
It seems like we are good with the modules we have integrated so far, so I close this.
