### ISSUE TITLE
Change sizing variants naming

### ISSUE THREAD

**Issue by csshugs** [inuitcss/inuitcss#400]
The scaling we currently use for the different scales of our spacing variables (e.g. `$inuit-global-spacing-unit-tiny`) and all the spacing variants classes of our objects (e.g. `.o-media--huge`) are not really scalable.

### Problem
E.g. when you have a project that needs an additional spacing variant that’s even smaller than `tiny`, how do you name it? `super-tiny`? `micky-mouse`? And what comes after that?

I know that this large variety of different spacings is most of the times really a design flaw and should not happen. I.e. if you have more than 5 different spacing variants in your project, you probably should reconsider your design decisions. But not every project is a dream project that just goes perfectly smooth from start to end. And maybe there are justified exceptions where you just need a few more spacing variants.

### Proposal
Instead of coming up with a new name for each smaller and larger variant, we could utilise the T-Shirt size scaling:

```
- ...
- $inuit-global-spacing-unit-xxsmall
- $inuit-global-spacing-unit-xsmall
- $inuit-global-spacing-unit-small
- $inuit-global-spacing-unit
- $inuit-global-spacing-unit-large
- $inuit-global-spacing-unit-xlarge
- $inuit-global-spacing-unit-xxlarge
- ...
```

This way, we can always add another variant at both ends of the scale easily.

### Remaining issues
The problem that still exists with either approach is adding a variant in between two existing variants. E.g.: How do we name an additional variant in between `small` and `xsmall`?

**Comment by andrejilderda** [comment]
Good one @csshugs! This is something I have run into myself and love to see solved.

**Comment by herzinger** [comment]
Soooo ugly hahahaha

No, but seriously, this is a non issue. Let's start from down: `$inuit-global-spacing-factor` is preset as 1. That means `$inuit-global-spacing-unit` is the same as the baseline grid's height. By definition you shouldn't be using any spacing lower than that to begin with, at the very least not in vertical spacing. That is not to say there's nothing lower than 6px or 8px in my projects (all of which at least strive to be 'dream projects'). I.e.: in the current one I define a `($inuit-global-baseline / 2)` border-radius for most containers, and it's defined in a `$global-border-radius` variable. So I don't think you need global spacing variables for anything lower than tiny, and I also think the whole "keeping to multiples of the baseline" is something inuitcss should enforce. But if you absolutely need namings for that, I'd suggest respectively `bit` and `plank` (the lowest unit of measurement possible in physics). Even if you're using a 8px baseline - the highest value I could recommend - the next decrement is 1px, and you don't need a variable for that.

Now for up: while much like temperatures, there's no absolute upper ceiling for that, I still believe it's mostly unneeded, but this is really easy to name anyway: `gigantic` and `gargantuan` are good enough. If you go past that, for this kind of white space you shouldn't really be using absolute sizing anymore. A vh based approach would make more sense, and your baseline should have a "per screen fold" context. 

Also, as I said, you can aways multiply any of the variables, or even the baseline, however you need. This will still keep to the grid, because math is beautiful like that.

Finally, my biggest problem with the suggested convention is that it's too visually similar, and not imediately descriptive enough. Maybe it's because t-shirts are not scaled like that in my country, but as a rule of thumb I don't like abbreviations in variable names.

**Comment by herzinger** [comment]
I'd like to address this as well:

> And maybe there are justified exceptions where you just need a few more spacing variants.

In such cases you should (and it's totally fine to) have a variable named for the exception, not create another rule to accommodate it. One exemple is the border-radius one I talked about before. 

But to keep to spacing, let's say the design asks for a REALLY cozy list, with a 120px margin-bottom between itens, in a 6px baseline. You could do a bunch of reverse engineering in the framework to accommodate a 20 spacing-factor, or simply define some larger spacing unit, yes. 

But what I would do is just define a `$cozy-list-spacing: ($inuit-global-baseline * 20)` variable and call it a day.

**Comment by florianbouvot** [comment]
For a long time, I work with inuitcss default (tiny to huge) but like @csshugs says every project are not dream project. Sometimes I can't use `line-height` for spacing because of client / designer choice...

Sometimes I start with base spacing (e.g.: 8px) and add options depending on project.
- Small needs: 8, 16, 32, 64px
- Big needs: 8, 16, 24, 32, 48, 64, 96px    
_I use 4px for typohgraphy_

Then I like to add extra variables like `$layout-gutter`, `$layout-gutter-narrow`, `$layout-gutter-wide` in objects/components to override default inuit spacing with project spacing.
 
About naming, I use and like short t-shirt size scale: xs, sm, md, lg, xl, 2xl, ...

**Comment by florianbouvot** [comment]
I'm ok to follow your proposal but only with xsmall to xlarge in the framework by default.

**Comment by nicoqh** [comment]
Either way, shouldn't `$inuit-spacing-sizes` be respected throughout objects *and* utilities?

I use the same naming convention for spacing utilities, responsive utilities, certain extensions etc. But objects that come out of the box have `.o-media--large` etc.

This doesn't look very good:

```html
<div class="o-layout--huge u-mb-xl">
</div>
```

**Comment by herzinger** [comment]
@nicoqh while you have the ability to change the class naming convention for map generated classes like the spacing utilities, today the default is the more verbose one used in the whole framework. In your example it would be `u-margin-bottom-huge`.

Back on topic, the main reasons I don't like those changes are: 
1. I prefer more verbose and easily distinguishable naming, even if it's longer; 
2. It's less accessible internationally. As I said before, xs, sm, md, lg, xsmal, xxlarge and the likes are gibberish in my country. Since other frameworks use stuff like that, one could argue the community already absorbed the meanings, but I still personally don't like it.

**Comment by csshugs** [comment]
IMO, this all boils down to the fact that we need a feature to define the set, as well as the naming for each entity of the spacing’s set ourselves, i.e. configure this all in a Sass map instead of defining plain variables for the spacings.

E.g.:

```scss
$inuit-global-baseline:     6px !default;

$inuit-spacings: (
    "base":  $inuit-global-baseline * 4,
    "tiny":  $inuit-global-baseline * 1,
    "small": $inuit-global-baseline * 2,
    "large": $inuit-global-baseline * 8,
    "huge":  $inuit-global-baseline * 16,
) !default;
```

This way, anyone can extend the list of spacings and name the individual variants how they want to, e.g.:

```scss
$inuit-global-baseline:     8px !default;

$inuit-spacings: (
    "xs":   $inuit-global-baseline * 1,
    "x":    $inuit-global-baseline * 2,
    "m":    $inuit-global-baseline * 4,
    "l":    $inuit-global-baseline * 8,
    "xl":   $inuit-global-baseline * 16,
    "xxl":  $inuit-global-baseline * 32,
    "xxxl": $inuit-global-baseline * 64,
) !default;
```

or:

```scss
$inuit-global-baseline:     4px !default;

$inuit-spacings: (
    "maggie": $inuit-global-baseline * 1,
    "lisa":   $inuit-global-baseline * 2,
    "bart":   $inuit-global-baseline * 4,
    "marge":  $inuit-global-baseline * 8,
    "homer":  $inuit-global-baseline * 16,
) !default;
```

**Comment by csshugs** [comment]
#420 is merged.
