### ISSUE TITLE
Responsive vertical spacing object

### ISSUE THREAD

**Issue by ajshortt** [inuitcss/inuitcss#408]
Over the last year or so, I keep adding a useful object of my own which helps utilise the spacing variables in the form of vertical padding. Much like the `o-box`, the proposed object applies padding to the desired element.

I know this might be another custom extension of inuit that won't be included in the package but as I keep using it, I felt I would share anyway.

**The Problem**
I often get designs given to me where modules and sections have certain vertical spacings on mobile, different on tablet, different on smallDesk and so on. These also don't often scale like you would expect.

**What is it?**
Simply put, it's an object that applies top and bottom padding to an element. The object is very similar to `o-box` but the difference is that the values are set in a map which allows for custom responsive spacing. The `@each` loop iterates in a mobile-first way so it takes each array item as a `$from` breakpoint.

**Debatable areas**
- I'm "ummming" and "ahhhhing" about the naming of the object so that's up for discussion.
- The functionality could also be integrated into the `o-box` object instead of it's own object via `--veritcal-only` and `--{spacing-type}` modifiers. 

Again, this is an object I use a lot so please feel free to shoot it down or embrace it :)

PR to follow

**Comment by rowild** [comment]
Sound exactly like the situations I find myself in very often. Would like to know you solution. Do you have any code to share?

**Comment by ajshortt** [comment]
@rowild I've just posted a PR. You're probably like me and hate trying to remember and putting...
```
<div class="u-margin-bottom-small u-margin-bottom@device u-margin-bottom-huge@desk"/>
```
So this instead allows the developer to map out common spacing patterns. I typically add these settings during the design to dev handover where we identify these patterns together. Unless there are edge-cases, this helps iron-out any inconsistencies.

So the above would look like
```
<div class="o-vertical-spacer--module"/>
```

What are your thoughts?

**Comment by herzinger** [comment]
Maybe I didn't understand it right, and I did just take a quick look, but I fail to see how this would be better or simpler than adding you own classes in the components - or even objects - level, or a custom mixim, even... I have to look at what code this generates later, but on a gut level, it sounds quite roundabout.

**Comment by ajshortt** [comment]
@herzinger I agree that it is simple to add these to own components but the point here is that you can abstract shared values and define patterns of spacings. So instead of `c-component-x`, `c-component-y`, `c-component-z` all having their own styles **and** their spacing, they would instead focus on their respective component self whilst leaving the vertical spacing the `o-vertical-spacer` object.

Maybe my implementation of the vertical-spacer object could be improved or even scrapped but the top-level issue that I come across is defining responsive spacing patterns. Maybe a tool might be useful as well to allow the usage of shared spacings within classes `@include responsive-padding('some-map');` on top of defined objects (in this case, `objects.vertical-spacer`). The spacings map could be used by `o-box` and other existing objects too.

**Comment by herzinger** [comment]
Yes, abstracting patterns is a good thing, and I did add the objects layer to the options because that is what it's for. The concept is solid, my issue is with the implementation and whether it should be a part of the framework or a per project addition. Maybe it would be better as a pure mixim instead of an object? I'm on my phone right now, going to work. I'll be able to form a better opinion by looking at the code and its output, then I'll get back to you.

**Comment by ajshortt** [comment]
Sure thing @herzinger. I can have another crack at making it a mixin for you and also look at making the setting a little more ingrained into the framework as an option instead of a partial settings file.

**Comment by ajshortt** [comment]
Ok, so this has been changed a little. The vertical spacer object has been removed and the spacing settings variable is now within the global.settings.scss file. 

Instead, a mixin has been made which applies the same concept as the vertical spacer but allows the developer to use in objects and components where they see fit.

@herzinger Let me know your thoughts. Cheers

**Comment by herzinger** [comment]
Okay, this is definitely better. There's some room for improvement still. Some things:

1. the name `$inuit-responsive-spacing-sizes` is alteady used, in `_utilities.responsive-spacings.scss`. Overall, that solution has some similarities with what you're trying to do, so I would look into merging both somehow, maybe. I'm not sure it's possible, but I would try.

2. You should so some verifications, with informative errors like: 
```scss
     @if (map_has_key($global-responsive-spacing-sizes, $map_key) == false) {
       @error "You forgot to set `#{$map_key}` in the $global-responsive-spacing-sizes map."
     }
```

3. Please, try and follow the variable's naming convention used in the framework. There are some similar patterns you can use as reference, like the responsive-spacings utilities generator I mentioned above.

4. I would love to see a version of this that would allow the same for margins, even if it added some complexity for the map, or maybe a second map if needed, but I see no need for a separated mixin to achieve that. Maybe this pattern might be an idea:
```scss
    #{$property}-bottom: $value;
    #{$property}-top: $value;
```

5. One problem I see is that the default map use explicitly the breakpoint names defined by sass-mq. If the user changes those names and/or have different breakpoints altogether, it would break. This could be mended by the approach I mentioned in number 2, but should also be mentioned in the comments. Also, maybe it would be a good idea to create a `_settings.responsive` to group all maps and variables necessary for all of the responsive features in the framework.

I might try and tackle those issues if I can free some time, but it's your brain child, so what do you think?

**Comment by ajshortt** [comment]
Thanks for the feedback @herzinger. I'm just powering my machine down for the evening but I'll pick this up tomorrow and tackle your points 👍.

Cheers!

**Comment by ajshortt** [comment]
...and I completely agree with all the improving points e.g incorporating margins for example. I'll have another fresh look tomorrow then get back to you.

**Comment by ajshortt** [comment]
@herzinger I've had a little blast at your points above. Here's a list of what I've done to help you review the code. Also, please point out any issues etc.

- Abstracted the values of `$inuit-spacing-directions` `$inuit-spacing-properties` and `$inuit-spacing-sizes` from `_utilities.spacings.scss` to `default` variables in  `settings.core` - Reason is so you can use these `normal` defaults in `settings.responsive` too.
- Added `settings/settings.responsive.scss with all responsive settings including default `mq-breakpoints`.
- Remove `$inuit-widths-breakpoint-separator` from `utilities.widths.scss` as it is now defined in the new responsive settings file.
- Amended comments in the `utilities.responsive-spacings.` file to help guide people to amend the relevant settings in `settings/_settings.responsive.scss` 
- And finally refactored my new spacing tool (`tools.spacing`) to utilise various responsive settings, to use any spacing property and amended comments to match 

Let me know what you think. I've also left the CHANGELOG until you've had a look 👍

**Comment by ajshortt** [comment]
I'm also thinking of extending the use of these changes into other areas e.g the `o-box` with a setting allowing a developer to use the new `$inuit-responsive-spacing-maps` values for the padding of the box

**Comment by herzinger** [comment]
I'm a bit strapped for time this week, but I'll take a look and get back to you as soon as I can (might have to be over the weekend, but I'll try and do it earlier). Superficially, just going by your bullet points, it sounds solid. It would be nice if @inuitcss/core could also take a look.

**Comment by ajshortt** [comment]
I will be too. I'm abroad till Sunday evening so I can pick up any further refinements then. Cheers man

**Comment by ajshortt** [comment]
Any update on this @herzinger ?

**Comment by herzinger** [comment]
Sorry, I've been really busy as of late, so I still didn't have the time to read and test it properly. In any case, we'll need the approval of the core team for it to be merged, but I'll try and look at it this week and get back to you.

**Comment by Jamiewarb** [comment]
Hey @herzinger!

Could I ask if anyone is looking at this issue, and what the status of it is, please? 😊

**Comment by hayatbiralem** [comment]
Hey guys!

I just want to look one of inuitcss issues from my inbox for some brainstorming and this one caught my attention.

First of all thanks for whole this work.

I looked the `@inuit-responsive-spacing` mixin and it looks great.

I'm not sure that would needed but I have two thoughts.

### Map scaffolding could handle different spacing values for the same direction like
`padding-top: 60px` but `padding-bottom: 30px`

Current `$inuit-responsive-spacing-maps` is like this:

```scss
$inuit-responsive-spacing-maps: (
  default-box: (
    mobile: 15px, /* padding-top: 15px; padding-bottom: 15px; */
    tablet: 30px,
    desktop: 45px,
    wide: 60px,
  ),
  huge-box: (
    mobile: 30px,
    tablet: 60px,
    desktop: 90px,
    wide: 120px,
  ),
);
```

which is goot imo but it could be more powerful when it covers different sizes like this way:

```scss
$inuit-responsive-spacing-maps: (
  default-box: (
    mobile: 15px, /* padding-top: 15px; padding-bottom: 15px; */
    tablet: 30px 45px, /* padding-top: 30px; padding-bottom: 45px; */
    desktop: 45px 60px,
    wide: 60px 90px,
  ),
  huge-box: (
    mobile: 30px,
    tablet: 60px 90px,
    desktop: 90px 120px,
    wide: 120px 150px,
  ),
);
```

I think `@inuit-responsive-spacing` mixin could handle both syntax with some little changes.

### Map scaffolding could handle different spacing values for all directions like
`padding: 60px 30px` or `padding: 10px 20px 30px 40px`

This could be more powerfull and easier because first need is that to make an object has responsive spacing workaround. With this way you could simply define responsive spacings for all directions at the same time becasue a box always has spacing at all directions so we could use `padding` or `margin` shorthand.

So `$inuit-responsive-spacing-maps` should look like this:

```scss
$inuit-responsive-spacing-maps: (
  default-box: (
    mobile: 15px 30px, /* padding: 15px 30px; */
    tablet: 30px 45px 60px 45px, /* padding: 30px 45px 60px 45px; */
    desktop: 45px 60px 90px 60px,
    wide: 60px 90px 120px 90px,
  ),
  huge-box: (
    mobile: 30px 45px,
    tablet: 60px 90px 120px 90px,
    desktop: 90px 120px 180px 120px,
    wide: 120px 150px 240px 150px,
  ),
);
```

This means the breakpoint value is gonna used as the property value.

If you need simple vertical and horizontal spacings you could simply use shomething like this:

```scss
$inuit-responsive-spacing-maps: (
  default-box: (
    mobile: 15px 30px, /* padding: 15px 30px; */
    tablet: 30px 45px, /* padding: 30px 45px; */
    desktop: 45px 60px,
    wide: 60px 90px,
  ),
  huge-box: (
    mobile: 30px 45px,
    tablet: 60px 90px,
    desktop: 90px 120px,
    wide: 120px 150px,
  ),
);
```

This code looks the same at the first thought but its usage is not. Be aware on that.

But I also want to avoid `padding` or `margin` shorthands because I know it is better to use `padding-top` or like. Maybe we could modify `$inuit-responsive-spacing-maps` and/or `@inuit-responsive-spacing` mixin to cover this with keeping all directions approach.

What do you think?

**Comment by ajshortt** [comment]
Hey Ömür,

I like the idea. The feature was initially created as I found myself requiring similar vertical spacing patterns and not box like spacing. As there is already `o-box` I felt that just a vertical spacer was enough but......I like the idea of making the response spacing map work on all directions or just one. 

I'll look at coding your idea this week sometime then get back to you.

Cheers

**Comment by herzinger** [comment]
I actually prefer the vertical only approach, as horizontal spacing should, in most cases, be handled by the grid (or is specific to the object/component, like with box or buttons). But yes, being able to set different values for top and bottom is essencial.

**Comment by csshugs** [comment]
I just riffled through this issue’s conversation again and for the life of me, I honestly cannot see any reason to add this functionality to the framework. To me, although this can be abstracted to be useful for many use cases, this is just too implementation-specific. Don’t get me wrong: this is an absolutely valid use case—it’s just not something inuitcss should handle.

As far as I initially understood your indent for this @ajshortt, it seems like you needed some context-sensitive spacings for individual components. This might be subjective, but I definitely would recommend doing this with a custom object that only handles the spacing and put the component into that object:

```html
<div class="o-section">
    <div class="c-component">
        ...
    </div>
</div>
```

For me, I have a guideline of never mix objects and components but always nest components **inside** objects. Also I try to stick to the convention of never assigning any _outer_ spacings to components, but to handle this via objects.

Apart from that, the proposed solution would not really make the code any cleaner and easier to read—rather to the contrary. Using an object on the other hand would not alter/complicate the existing code at all.

I’m really sorry because I can see all the work that you put into this, but this is just a bit too specific to become a part of the framework. However we’d love to see this provided as an inuitcss plugin if you like, as we are sure there are other inuitcss users that could find a use case for this.

**Comment by ajshortt** [comment]
Hey @csshugs 

No worries. This was started over a year ago and much has changed since then. For me, this issue is now solved by a Vue component so like you have said, this is probably a little too precise to live within the framework.

Thanks for hacking through all the issues. Keep up the good work 👍
