### ISSUE TITLE
Separate functions and mixins tools into independent files

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/inuitcss#5]
Far from being a priority, I wonder if it would be efficient to split `tools.functions` and `tools.mixins` into independent files ?

e.g.:
`tools.maths`
`tools.font-size`
`tools.clearfix`
...

**Comment by csshugs** [comment]
@inuitcss/core 
In my current project, we already have 9 mixins, all separated in individual files. If we would squeeze them all in one `tools.mixins.scss`, that would be 450 lines of code (including documentation .. much documentation, I proud to say 😄 ). That would be huge and that's the reason I like to put my mixins into independent files.

@csswizardry That's why I (as an inuitcss user) would not follow your official advice above, because my single `tools.mixins.scss` would just be too confusingly long. I separate them.

What I like about the approach of separating the mixins into their own appropriate files is the modularity it provides. You can opt-out of certain mixins if you do not need/want them. E.g. if I don't want the `hidden-visually` mixin (for whatever reason) which is currently in inuitcss' `tools.mixins.scss`, I can't. I get either all mixins, or none at all. 
If every mixin gets its own partial, I pick those mixins I need, and omit those I don't. That's the same principle we already practice in the rest of the framework anyway. I mean we don't have all the objects in one single file. I know, a bit exaggerating, but IMO the principle is transferable.

So here's my proposal:
```
@import "bower_components/inuitcss/tools/tools.font-size";
@import "bower_components/inuitcss/tools/tools.clearfix";
@import "bower_components/inuitcss/tools/tools.hidden-visually";
@import "tools/tools.some";
@import "tools/tools.crazy";
@import "tools/tools.mixins";
```

**Comment by erfanimani** [comment]
I tend to agree with @csshugs , I usually do something like this (copied from an actual project):

    @import "bower_components/inuit-functions/tools.functions";
    @import "bower_components/inuit-tools-widths/tools.widths";
    @import "bower_components/inuit-mixins/tools.mixins";
    @import "bower_components/inuit-responsive-tools/tools.responsive";
    @import "tools/*";

**Comment by LayZeeDK** [comment]
Somehow it should be clarified to users that the font-size, and clearfix tools are required for certain parts of the framework. Is it enough that a Sass compiler warns for a missing mixin or function?

**Comment by csshugs** [comment]
I just realized that `_tools.widths` never was in `_tools.mixins` but always was an extra partial, which kinda supports my point of [splitting them all into separate files](https://github.com/inuitcss/inuitcss/commit/26d2d88dc956cb55c1d0d2f38116523e4e049951).

When you [have a look at my commit](https://github.com/inuitcss/inuitcss/commit/26d2d88dc956cb55c1d0d2f38116523e4e049951), you'll see that there are now [four more includes](https://github.com/inuitcss/inuitcss/blob/26d2d88dc956cb55c1d0d2f38116523e4e049951/example.main.scss#L90-L97) than there were before.
**But** I think we can get rid of `inuit-hocus` function (kinda opinionated) and `inuit-havle` function (still don't know what that is for). Furthermore I guess that we can also ["get rid" of the widths-mixin as a single file](https://github.com/inuitcss/inuitcss/issues/117).

Apart from this, it feels much more modular and tidy to me to have it all separated logically.

@inuitcss/core What do you think by [having a look at the changes](https://github.com/inuitcss/inuitcss/commit/26d2d88dc956cb55c1d0d2f38116523e4e049951)?

**Comment by florianbouvot** [comment]
> `inuit-halve` function (still don't know what that is for)

`inuit-halve` refer to old [math tools](https://github.com/inuitcss/tools.functions/blob/master/_tools.functions.scss).

LGTM, I think we can remove `inuit-halve` and may be `inuit-hocus` too.

**Comment by florianbouvot** [comment]
refs #92

**Comment by nenadjelovac** [comment]
@csshugs I think we should remove everything we are not using now (halve and hocus).

The only comment that I have is that there is no difference between functions and mixins in filenames, which might take a way a bit of clarity. I think there was an suggestion to name it like this for example:

- `_tools.function.rem.scss` 
- `_tools.mixin.font-size.scss`. 

Also, I think it was you @csshugs that actually had that suggestion in one of the issues in last version of inuitcss

**Comment by anselmh** [comment]
Except for the `hidden-visually` partial that’s an improvement. For the mentioned partial I think we should call it more generic like `hidden` so that it can contain more than just this one mixin but multiple?

**Comment by nenadjelovac** [comment]
@anselmh good spot! I second that suggestion.

**Comment by csshugs** [comment]
@nenadjelovac 

> * _tools.function.rem.scss
> * _tools.mixin.font-size.scss.

> Also, I think it was you @csshugs that actually had that suggestion in one of the issues in last version of inuitcss ;)

Yeah, I remember that and thought about doing it here, too. But I considered this to be an extra issue, which I would open when this issue is approved.

@anselmh 

> For the mentioned partial I think we should call it more generic like hidden so that it can contain more than just this one mixin but multiple?

I like that. I'll correct that in a minute.

**Comment by nenadjelovac** [comment]
@csshugs ah, ok. So pls raise an issue then ;)

**Comment by csshugs** [comment]
@nenadjelovac One thing at a time 😄

**Comment by csshugs** [comment]
> I think we should remove everything we are not using now (halve and hocus).

Let's open an extra issue for removing `inuit-hocus` function.

You'll find the issue questioning `inuit-halve` function [here](https://github.com/inuitcss/inuitcss/issues/92).

**Comment by csshugs** [comment]
Since #118 is merged, I close this.
