### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#58]
We need at least a better README until we get the site done. I’ll make a start on that :)

**Comment by csshugs** [comment]
Thumbs up for adding a few words on how to write "inuitcss" correctly (not inuit nor inuitCSS nor Inuitcss nor InuitCSS). I just hate it when people doing those things wrong. ([Related](http://sassnotsass.com/))

**Comment by csshugs** [comment]
> I just hate it when people doing those things wrong.

Sorry for being so german.

**Comment by zerodburn** [comment]
One thing that confused me a bit when I first started using inuitcss was adding the enabler variables like `$enable-layout--flush: true;` in your main.scss file before including _objects.layout.scss. So along with @nenadjelovac's suggestion of a main.scss file I would include at least one example of one of those enabler variables (sorry I'm sure there's a better/official term for them but I'm on a dodgy train 3g connection at the mo!)

**Comment by csshugs** [comment]
@zerodburn 
Actually, there is no need for that, since the new version of inuitcss does not provide such variables anymore. In the example of the layout object, all modifiers are on by default and there is no way to opt-out anymore.

**Comment by csshugs** [comment]
[See here](https://github.com/inuitcss/inuitcss/blob/36c24d40ad871facc35f3852f5bba0e0567b4e3d/objects/_objects.layout.scss#L120-L167)

**Comment by zerodburn** [comment]
Oh ok sorry, I need to get to grips with the new version before making more
suggestions obviously :)

Cheers,

Patrick

**Comment by dnixx** [comment]
I think the list should also include how to configure the framework and your own project (and the distinction). Perhaps this is included in the item "*Moving example files around*".

But still, `settings.core` includes essential framework variables that shouldn't be edited (but preconfigured). However, halfway down the file it says "DO NOT MODIFY ANYTHING BEYOND THIS POINT", which I think may cause some confusion.

**Comment by nenadjelovac** [comment]
@dnixx 

>"DO NOT MODIFY ANYTHING BEYOND THIS POINT"

I think this is leftover from previous version that got through code review somehow :) @csswizardry is that the case?

**Comment by area73** [comment]
Hi @csshugs , I was wondering why you guys decide to get rid of all the optional variables. I though it was a great idea not to have code in you css if you are not going to use it, maybe I'm missing something?

**Comment by zerodburn** [comment]
@area73 from the latest commit on example.main.scss, it looks like @csswizardry has added one in: https://github.com/inuitcss/inuitcss/commit/72781f2e424e7713f88d3d876db1066627d26d98 It must be because offsets output a fairly large chunk of CSS.

**Comment by herzinger** [comment]
I also would like to know why the optional vars are gone. I've been following inuit for a long time now, since the first repo, but it's being some time since I checked it, so I've missed that change (I didn't even see this 'united' repository until today, and am currently developing a big project with the old modules). I quite like the optional stuff, to be honest.

**Comment by csshugs** [comment]
@zerodburn 

> @area73 from the latest commit on example.main.scss, it looks like @csswizardry has added one in: 72781f2 It must be because offsets output a fairly large chunk of CSS.

Correct. This is an exception for `push/pull`. 

We wanted to make the new version of inuitcss even tinier with a much more simpler Sass code which led us to the decision of dropping all those vars and make the appearance of the Sass code much more clearly to everyone. This will increase the filesize to an incredibly small amount but not more, because we are also just adding very granular things to the framework that are essential to almost every project. On top of that, I guess @csswizardry can tell you guys the relevant points to gzip compression of CSS files, in case your are afraid of CSS bloat.

If you are still concerned about this, please file a dedicated issue for that specific issue and we can discuss that in more detail.

**Comment by csshugs** [comment]
@inuitcss/core 
I've now worked off [the checklist](https://github.com/inuitcss/inuitcss/issues/58#issuecomment-229699216) from the top, except the point about ITCSS, because @csswizardry was not sure about how much information he will give away for free in the context of the inuitcss documentation.
But I added a section about the directory structure and a short paragraph about namespaces in classnames. Maybe that's sufficient for now, concerning principles/ITCSS in combination with inuitcss. Also, this is "just" a README for now. The final documentation will contain much more information, for sure.

@inuitcss/core What do you think? Anything to add [here](https://github.com/inuitcss/inuitcss/tree/tkt-0058)?

**Comment by herzinger** [comment]
So, I went and did a little bit of [asking around](https://github.com/SassDoc/sassdoc/issues/467), and then went and did [this](https://www.npmjs.com/package/inuit-sassdoc). 

I did not have the time to test it out yet, but I think it's worth the try, right?

**Comment by csshugs** [comment]
@herzinger 
As already discussed in #150 and #164, we will not use SassDoc. It's not only the commenting style, but rather the necessity of using SassDoc at all (even if the commenting style would not be an issue). inuitcss has very little Sass functionality. Too little to justify the usage of SassDoc.

Thanks for your effort of working out a solution, though!

**Comment by csshugs** [comment]
Since [the current documentation](https://github.com/inuitcss/inuitcss/blob/126bebe2ff2146b7101ef28fb1b2c0c4832261dc/README.md) in the form of a README.md seems to be sufficient for now, I close this.

**Comment by herzinger** [comment]
I don't agree it's too little, but even when assuming so, inuitcss is a framework, not meant to be used by itself. It's actually meant for large projects, so in the wild it will often be among large codebases that ideally should be documented in an automatized way. When that happens, it'll get in the way of documenting the parts that come from inuitcss, and that are the building blocks of the project.

To be honest, I rank SassDoc support high enough to justify printing the comments to the output, seeing as almost every production code would be minimized. But that fork even removes this requirement, so I'm REALLY in favor of using it.
