### ISSUE TITLE
[objects.flag] Port flag object over

### ISSUE THREAD

**Issue by csswizardry** [inuitcss/inuitcss#76]
What outstanding bugs/issues are there with the flag object?

**Comment by florianbouvot** [comment]
@nenadjelovac report a bug [here](https://github.com/inuitcss/objects.flag/issues/5)

**Comment by csswizardry** [comment]
I’m struggling to distill the problem and its fix into anything simple. The flag object is meant to take up 100% width (like the media object would), so I don’t think this is a problem with the flag object per se; it’s actually Just How Tables Work™.

Unless you specify `table-layout: fixed;` the cell with the largest content will take up all available space (even wrapping other cells’ content onto multiple lines).

Happy for any other input or feedback :)

**Comment by nenadjelovac** [comment]
@csswizardry ok, maybe I haven't been clear enough. The problem occurs when flag is within `display: inline-block` or `display: table-cell` parent. In that case Webkit/blink based browsers render the code differently than other browsers.

Here's an example of a flag within `.layout--auto` http://codepen.io/nenadjelovac/pen/zBPrAo. Try opening this example in FF and in Chrome. Now, here's the fix http://codepen.io/nenadjelovac/pen/BzmGLb. 

As I said in other issue, the fix is to set `width: 1px` to `.flag__img` and remove `width: 100%` from `.flag__body`. I have picked up the fix from [an old(ish) article here](http://pixelsvsbytes.com/blog/2012/02/this-css-layout-grid-is-no-holy-grail/?phpMyAdmin=0ZRJj6JUwx3do5nBBGsib-MdEm7). Here's what the author has to say about this:

> **By setting height/width:1px a normal cell will use the minimum amount of space to display its contents**, leaving all unused space for the .Expand class cells with height/width:auto.

Does this help with this:
>I’m struggling to distill the problem and its fix into anything simple. 

?

**Comment by csswizardry** [comment]
Any thoughts on f000350, @nenadjelovac?

**Comment by nenadjelovac** [comment]
@csswizardry that should do it.

**Comment by csswizardry** [comment]
It seems to work as well. I’ll open a PR. Thanks! :+1:
